### PR TITLE
Fix props error for first login  confirmation steps

### LINKED ISSUE #3270: (SP:) Fix errors in `UserStepsWrapper` component
Fix occurred errors in UserStepsWrapper component

Path:
Image

Code:
Image

Errors:
Image

### PR DESCRIPTION
**Pull request by yur4uwe**
- In components corresponding to first login steps made props optional to eliminate the error

With limited knowledge at hand i checked via Chrome browser(Version 134.0.6998.178 (Official Build) (64-bit version)) and didn`t spot any issues

After Change ( Student )

image

After Change ( Tutor )

image

### CODE REVIEW

File: src/components/user-steps-wrapper/UserStepsWrapper.tsx [hunk 1]
```diff
@@ -29,10 +29,10 @@ const UserStepsWrapper: React.FC<UserStepsWrapperProps> = ({ userRole }) => {
...
 
   const childrenArr = [
-    <GeneralInfoStep key='1' />,
-    <SubjectsStep key='2' />,
-    <LanguageStep key='3' />,
-    <AddPhotoStep key='4' />
+    <GeneralInfoStep btnsBox={undefined} key='1' />,
+    <SubjectsStep btnsBox={undefined} key='2' />,
+    <LanguageStep btnsBox={undefined} key='3' />,
+    <AddPhotoStep btnsBox={undefined} key='4' />
```
Comment (ArtemHolikov) [inline src/components/user-steps-wrapper/UserStepsWrapper.tsx]:
```suggestion
    <GeneralInfoStep key='1' />,
    <SubjectsStep key='2' />,
    <LanguageStep key='3' />,
    <AddPhotoStep key='4' />
```

It's not good to throw ```undefined```. If you set props with ? ( like in SubjectStep component you did ) it means that it's unneccessary to throw props and you can just not pass them.

File: src/containers/tutor-home-page/subjects-step/SubjectsStep.tsx [hunk 2]
```diff
@@ -19,7 +19,7 @@ import { subjectService } from '~/services/subject-service'
 import { CategoryNameInterface, SubjectNameInterface } from '~/types'
 
 interface SubjectsStepProps {
-  btnsBox: JSX.Element
+  btnsBox?: JSX.Element
```
Comment (ArtemHolikov) [inline src/containers/tutor-home-page/subjects-step/SubjectsStep.tsx]: Please, check in other 3 components and fix it.

**Review by ArtemHolikov — CHANGES_REQUESTED** [review]

File: src/containers/tutor-home-page/subjects-step/SubjectsStep.tsx (hunk 2 above)
Comment (yur4uwe) [reply src/containers/tutor-home-page/subjects-step/SubjectsStep.tsx]: Already fixed

File: src/components/user-steps-wrapper/UserStepsWrapper.tsx (hunk 1 above)
Comment (yur4uwe) [reply src/components/user-steps-wrapper/UserStepsWrapper.tsx]: Already fixed, thanks for suggestion

**Review by ArtemHolikov — APPROVED** [review]

File: src/containers/tutor-home-page/subjects-step/SubjectsStep.tsx (hunk 2 above)
Comment (Mike-Popovych) [inline src/containers/tutor-home-page/subjects-step/SubjectsStep.tsx]:
```suggestion
  btnsBox?: React.ReactNode
```

**Review by SofiiaYevush — APPROVED** [review]

**Review by markgol777 — APPROVED** [review]
