### PR TITLE
Fix pagination scroll on "Find offers" page

### LINKED ISSUE #2424: (SP: 0.5) Fix pagination scroll on "Find offers" page
Expected result: 
Pagination should scroll to the filter instead of to the top of the page

Actual:

https://github.com/user-attachments/assets/7c864736-754d-49b4-9811-eedf69e8f177

### PR DESCRIPTION
**Pull request by BohdanMylyi**
Made FilterBarMenu like target block for pagination scroll. 
Also add swooth behavior for scroll.

Actual result:

https://github.com/user-attachments/assets/f5bbaef0-6ea7-4bf9-9326-e74f22d25a47

### CODE REVIEW

File: src/containers/find-offer/filter-bar-menu/FilterBarMenu.tsx [hunk 1]
```diff
@@ -31,70 +31,78 @@ interface FilterBarMenuProps {
...
+              <ViewSwitcher onChange={handleOffersView} value={offersView} />
+            ) : null}
+          </Box>
+        ) : null}
+      </Box>
+    )
+  }
+)
+
+FilterBarMenu.displayName = 'FilterBarMenu'
```
Comment (ipasic-softserve) [inline src/containers/find-offer/filter-bar-menu/FilterBarMenu.tsx:106]: Do we need this line here?

**Review by docia — APPROVED** [review]

File: src/containers/find-offer/filter-bar-menu/FilterBarMenu.tsx (hunk 1 above)
Comment (BohdanMylyi) [reply src/containers/find-offer/filter-bar-menu/FilterBarMenu.tsx:106]: just for better readability

**Comment by YaroslavChuiko** [comment]
You need to link an issue to this PR

**Review by YaroslavChuiko — APPROVED** [review]

**Review by YulichkaR — APPROVED** [review]
