### PR TITLE
Fixed profile editing

### LINKED ISSUE #3141: (SP: ) Fix update button on EditProfile page
Actual result: after providing changes to Edit Profile, switching to other Tab and click to Update button our changed data was updated, but on the other hand, after reloading the page info didn't update.

https://github.com/user-attachments/assets/bf83cc1a-d690-446a-bd59-8fcec711c115

### PR DESCRIPTION
**Pull request by PavloButynets**
This PR depends on [Backend PR #1180](https://github.com/ita-social-projects/SpaceToStudy-BackEnd/pull/1180).
Merge the backend PR first to avoid breaking changes.

When sending a request to the server, the entire `profileState` object was sent, even those fields that were not edited, so a validation error occurred on the server because some fields (for example, `professionalSummary`, `nativeLanguage`) were empty strings. I also found another bug, when a user wanted to clear `professionalSummary` or `nativeLanguage`, he could not do it, because a request was also sent with an empty string and an error was thrown on the server. I implemented the request in such a way that only those fields that have changed are sent, and if the field is an **empty string** (“”), then **null** is sent

- Before:

https://github.com/user-attachments/assets/e15c7bd9-4621-4490-b481-2c7078f81398

- After

https://github.com/user-attachments/assets/f010fb7c-0836-4c23-9d63-c7dc212b2914

### CODE REVIEW

**Review by ArtemHolikov — APPROVED** [review]

**Review by SofiiaYevush — APPROVED** [review]

**Review by markgol777 — APPROVED** [review]

File: src/pages/edit-profile/EditProfile.tsx [hunk 1]
```diff
@@ -102,36 +95,11 @@ const EditProfile = () => {
...
-      }
-
-      return changes
-    } else {
-      return {}
-    }
+    return getChangedFields(
+      initialEditProfileState,
+      profileState
+    ) as Partial<EditProfileState>
```
Comment (ShadowOfTheSpace) [inline src/pages/edit-profile/EditProfile.tsx]: Why do you need type assertion here?

File: src/pages/edit-profile/EditProfile.tsx [hunk 2]
```diff
@@ -193,13 +161,19 @@ const EditProfile = () => {
     if (typeof photo === 'object' || photo === '') {
       dataToUpdate.photo = photo
     }
-
+    const dataWithoutEmptyStrings = Object.fromEntries(
+      Object.entries(dataToUpdate).map(([key, value]) => [
+        key,
+        value === '' ? null : value
+      ])
+    )
```
Comment (ShadowOfTheSpace) [inline src/pages/edit-profile/EditProfile.tsx]: You can extract that as a utility function, it will be used a lot in our project I think.

File: src/utils/get-changed-fields.ts [hunk 3]
```diff
@@ -0,0 +1,26 @@
+type Nullable<T> = {
+  [K in keyof T]: T[K] | null
+}
```
Comment (ShadowOfTheSpace) [inline src/utils/get-changed-fields.ts]: You don't need that type here.

```suggestion
```

File: src/utils/get-changed-fields.ts [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+
+export function getChangedFields<T>(
+  initialState: T | null,
+  currentState: T | null
+): Partial<Nullable<T>> {
```
Comment (ShadowOfTheSpace) [inline src/utils/get-changed-fields.ts]:
```suggestion
): Partial<T> {
```

File: src/utils/get-changed-fields.ts [hunk 5]
```diff
@@ -0,0 +1,26 @@
+type Nullable<T> = {
+  [K in keyof T]: T[K] | null
+}
+
+export function getChangedFields<T>(
+  initialState: T | null,
+  currentState: T | null
```
Comment (ShadowOfTheSpace) [inline src/utils/get-changed-fields.ts]: I thought we discussed that before: you don't need to get changes of objects that have different types.
What is the difference between `{ field: 'value' }` and `null` and otherwise? I think it only matters to find the difference between equal types.

File: src/utils/get-changed-fields.ts [hunk 6]
```diff
@@ -0,0 +1,26 @@
+type Nullable<T> = {
+  [K in keyof T]: T[K] | null
+}
+
+export function getChangedFields<T>(
```
Comment (ShadowOfTheSpace) [inline src/utils/get-changed-fields.ts]: Why you didn't specify a more detailed generic type here? Just `T` can be anything, I can pass here a plain string, array, or something else. I think we should make that forbidden here.

```suggestion
export function getChangedFields<T extends Record<string, unknown>>(
```

File: src/utils/get-changed-fields.ts [hunk 7]
```diff
@@ -0,0 +1,26 @@
...
+
+  const changes: Partial<Nullable<T>> = {}
+
+  Object.keys(currentState).forEach((key) => {
+    const typedKey = key as keyof T
+    const initialValue = initialState[typedKey]
+    const currentValue = currentState[typedKey]
+
+    if (
+      (currentValue !== undefined || initialValue !== undefined) &&
```
Comment (ShadowOfTheSpace) [inline src/utils/get-changed-fields.ts]: Why to we need to run `JSON.stringify` for undefined and defined fields?

**Review by ShadowOfTheSpace — CHANGES_REQUESTED** [review]

File: src/utils/get-changed-fields.ts (hunk 3 above)
Comment (PavloButynets) [reply src/utils/get-changed-fields.ts]: yes, I removed the null setting and forgot to remove this type

File: src/utils/get-changed-fields.ts (hunk 7 above)
Comment (PavloButynets) [reply src/utils/get-changed-fields.ts]: sorry, now it isn't necessary

File: src/pages/edit-profile/EditProfile.tsx [hunk 8]
```diff
@@ -102,36 +96,9 @@ const EditProfile = () => {
...
-      if (hasPhotoChanged) {
-        changes.photo = currentPhoto
-      }
-
-      return changes
-    } else {
-      return {}
-    }
+    if (!profileState || !initialEditProfileState) return {}
+    return getChangedFields(initialEditProfileState, profileState)
```
Comment (ShadowOfTheSpace) [inline src/pages/edit-profile/EditProfile.tsx]:
```suggestion
    if (!profileState || !initialEditProfileState) { 
    return {}
    }
    
    return getChangedFields(initialEditProfileState, profileState)
```

File: src/pages/edit-profile/EditProfile.tsx [hunk 9]
```diff
@@ -193,13 +160,14 @@ const EditProfile = () => {
     if (typeof photo === 'object' || photo === '') {
       dataToUpdate.photo = photo
     }
-
+    const dataWithoutEmptyStrings = replaceEmptyStringsWithNull(dataToUpdate)
```
Comment (ShadowOfTheSpace) [inline src/pages/edit-profile/EditProfile.tsx:167]:
```suggestion

    const dataWithoutEmptyStrings = replaceEmptyStringsWithNull(dataToUpdate)
    
```

File: src/utils/get-changed-fields.ts [hunk 10]
```diff
@@ -0,0 +1,19 @@
...
+  Object.keys(currentState).forEach((key) => {
+    const typedKey = key as keyof T
+    const initialValue = initialState[typedKey]
+    const currentValue = currentState[typedKey]
+
+    if (JSON.stringify(initialValue) !== JSON.stringify(currentValue)) {
+      changes[typedKey] = currentValue
+    }
+  })
+  return changes
```
Comment (ShadowOfTheSpace) [inline src/utils/get-changed-fields.ts:17]:
```suggestion

  return changes
```

**Review by ShadowOfTheSpace — APPROVED** [review]
Approved, but fix those comments about code style, please)
