### PR TITLE
( SP: 1) Fixed toggling bookmark on OfferDetails

### LINKED ISSUE #2450: (SP: 1) Fix bookmark saving on the OfferDetails page.
**How to find a bug:** 
All offers - View Details ( on any offer ) - toggle bookmark ( it won't be toggling )

https://github.com/user-attachments/assets/7efba640-f71e-445d-b53e-d43ee3b318c1

- [ ] ensure that the bookmark can be toggled on the OfferDetails page.

### PR DESCRIPTION
**Pull request by docia**
### Before: 
If the user clicks on View Details on the Offers page, the Bookmark won't work for toggling.

https://github.com/user-attachments/assets/074e3afa-2792-49bf-815d-c2507d7b5b41

### After: 
- [x] The Bookmark can be toggled successfully on the OfferDetails page. 

https://github.com/user-attachments/assets/a1f4dd27-48bd-4dd3-9426-b5aad89e655b

PS. please don't pay attention that I refresh the page after clicking a bookmark. there is a local issue on my PC. it should be working properly on your end.

### CODE REVIEW

File: src/utils/toggle-bookmark.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
+import useAxios from '~/hooks/use-axios'
+import { userService } from '~/services/user-service'
+import { UseAxiosProps } from '~/hooks/use-axios'
```
Comment (ipasic-softserve) [inline src/utils/toggle-bookmark.ts]: import `useAxios` and `UseAxiosProps` at the same place instead

Comment (docia) [reply src/utils/toggle-bookmark.ts]: good point, thanks. done.

**Review by Olenka-Hryk — APPROVED** [review]

**Review by OliaHrytsak — APPROVED** [review]

**Comment by OliaHrytsak** [comment]
Why useToggleBookmark  is util but not a hook?
And don't forget about tests

**Review by BohdanMylyi — APPROVED** [review]

**Review by ipasic-softserve — APPROVED** [review]
