### PR TITLE
Fixed drag-and-drop in cooperation activities modules in statuses of resources

### LINKED ISSUE #2865: Fix resource status is changing to "open" on drag and drop
On drag and drop, the resource status is changed to "open" for "closed" or "opened from" resources. This is not the expected behavior. The resource status should not be changed on drag and drop.

Expected result:

The status of the resource (Closed or Opened from) should not change on drag and drop.

Actual result:

The status of the resource changes to "Open" on drag and drop.

Demo:

https://github.com/user-attachments/assets/374f8547-0db1-4a04-a5f4-cafe46679e7b

https://github.com/user-attachments/assets/b6a13823-6314-4042-8c84-d6c3cc71d335

### LINKED ISSUE #3028: [Cooperation Activities] Verify if tutor can drag and drop resources in module without changing status.
Preconditions:

The user is logged in https://s2s-front-stage.azurewebsites.net/tutor as a Tutor/Student.
“Cooperations” => Choose existing cooperation => Choose module with resources => 'Edit'.
Test Steps:

Move resource to other place in module
Expected result:
Resource moved to other place correctly and doesn't changed it status.

### PR DESCRIPTION
**Pull request by amoutens**
Fixed changing statuses of resources in cooperation activities modules. Before: after any drag-and-drop every status is changing to Open. After fix: we can change order of resources in module without changing to Open

image
image
image
image
image

### CODE REVIEW

File: src/containers/course-section/resource-item/ResourceItem.tsx [hunk 1]
```diff
@@ -111,14 +107,18 @@ const ResourceItem: FC<ResourceItemProps> = ({
...
       })
     },
     [resource, updateAvailability]
   )
-
+  useEffect(() => {
+    if (resourcesAvailability === ResourcesAvailabilityEnum.OpenManually) {
+      setAvailabilityStatus(ResourceAvailabilityStatusEnum.Closed)
+    }
+  }, [resourcesAvailability, setAvailabilityStatus])
```
Comment (ShadowOfTheSpace) [inline src/containers/course-section/resource-item/ResourceItem.tsx]: Never use `useEffect` with updating state inside. It will cause an infinite loop

https://github.com/user-attachments/assets/f70cdefc-5c48-4949-9fa6-184a9e3d44d3

File: src/containers/course-section/resource-item/ResourceItem.tsx [hunk 2]
```diff
@@ -93,9 +87,11 @@ const ResourceItem: FC<ResourceItemProps> = ({
...
     return resourceIcons[type] ?? null
   }, [resourceType, resource.resourceType])
-
-  const status = availability?.status ?? ResourceAvailabilityStatusEnum.Open
-
+  const status = Object.values(ResourceAvailabilityStatusEnum).includes(
+    availability?.status as ResourceAvailabilityStatusEnum
+  )
+    ? (availability?.status as ResourceAvailabilityStatusEnum)
+    : ResourceAvailabilityStatusEnum.Closed
```
Comment (ShadowOfTheSpace) [inline src/containers/course-section/resource-item/ResourceItem.tsx]: Why did you changed that?

File: src/containers/course-section/resource-item/ResourceItem.tsx [hunk 3]
```diff
@@ -111,14 +107,18 @@ const ResourceItem: FC<ResourceItemProps> = ({
 
   const setAvailabilityStatus = useCallback(
     (status: ResourceAvailabilityStatusEnum) => {
-      updateAvailability?.(resource, {
+      return updateAvailability?.(resource, {
```
Comment (ShadowOfTheSpace) [inline src/containers/course-section/resource-item/ResourceItem.tsx]: Where do you use that returned value?

File: src/containers/course-section/resources-list/ResourcesList.tsx [hunk 4]
```diff
@@ -53,7 +48,35 @@ const ResourcesList: FC<ResourcesListProps> = ({
...
+      )
+      inactiveResources.forEach((inactiveResource) => {
+        if (inactiveResource.availability && updateAvailability) {
+          updateAvailability(
+            inactiveResource.resource,
+            inactiveResource.availability
+          )
+        }
+      })
+    },
```
Comment (ShadowOfTheSpace) [inline src/containers/course-section/resources-list/ResourcesList.tsx]: You should add availability to `CourseResource` type (because each resource contains `availability` field in our db) instead of this. So if you will change an order of the resource, you will change it with `availability` consistently.

**Review by ShadowOfTheSpace — CHANGES_REQUESTED** [review]

**Comment by ShadowOfTheSpace** [comment]
Why do you need [this](https://github.com/ita-social-projects/SpaceToStudy-Client/issues/3028) issue? Probably [that](https://github.com/ita-social-projects/SpaceToStudy-Client/issues/2865) issue already described this problem.

Also, please, update your branch with develop one, it's not up to date

File: src/containers/course-section/resource-item/ResourceItem.tsx (hunk 1 above)
Comment (amoutens) [reply src/containers/course-section/resource-item/ResourceItem.tsx]: this useEffect was used before mine. I only fixed eslint using. But thanks, I`ll check it

File: src/containers/course-section/resource-item/ResourceItem.tsx (hunk 2 above)
Comment (amoutens) [reply src/containers/course-section/resource-item/ResourceItem.tsx]: Because there was statement which manually set status on Open. I replace that statement with changing to current status or if we are having null, we'll get Closed status

File: src/containers/course-section/resources-list/ResourcesList.tsx (hunk 4 above)
Comment (amoutens) [reply src/containers/course-section/resources-list/ResourcesList.tsx]: Ok, thanks

**Comment by amoutens** [comment]
> Why do you need [this](https://github.com/ita-social-projects/SpaceToStudy-Client/issues/3028) issue? Probably [that](https://github.com/ita-social-projects/SpaceToStudy-Client/issues/2865) issue already described this problem.
> 
> Also, please, update your branch with develop one, it's not up to date

In my opinion, it is better add a new issue related to test coverage, because [this issue](https://github.com/ita-social-projects/SpaceToStudy-Client/issues/2865) doesn't describe test coverage

File: src/containers/course-section/resource-item/ResourceItem.tsx (hunk 3 above)
Comment (amoutens) [reply src/containers/course-section/resource-item/ResourceItem.tsx]: sorry, forgot to remove this

File: src/components/drag-handle/DragHandle.tsx [hunk 5]
```diff
@@ -15,7 +15,13 @@ interface DragHandleProps {
 const DragHandle: FC<DragHandleProps> = ({ iconStyles, wrapperStyles }) => {
   const { attributes, listeners, ref } = useSortableItemContext()
   return (
-    <Box ref={ref} sx={wrapperStyles} {...attributes} {...listeners}>
+    <Box
+      data-testid={`drag-handle`}
```
Comment (ShadowOfTheSpace) [inline src/components/drag-handle/DragHandle.tsx]:
```suggestion
      data-testid='drag-handle'
```

File: src/containers/course-section/resources-list/ResourcesList.tsx [hunk 6]
```diff
@@ -95,15 +135,15 @@ const ResourcesList: FC<ResourcesListProps> = ({
       </SortableContext>
       <DragOverlay>
         {activeItem &&
-          renderItem(
+          renderNewItem(
             activeItem,
-            { status: ResourceAvailabilityStatusEnum.Open, date: null },
+            activeItem.availability ||
```
Comment (ShadowOfTheSpace) [inline src/containers/course-section/resources-list/ResourcesList.tsx]:
```suggestion
            activeItem.availability ??
```

**Review by ShadowOfTheSpace — CHANGES_REQUESTED** [review]

File: src/components/drag-handle/DragHandle.tsx (hunk 5 above)
Comment (amoutens) [reply src/components/drag-handle/DragHandle.tsx]: oh, thanks!

**Review by luiqor — APPROVED** [review]

**Review by SofiiaYevush — APPROVED** [review]

File: tests/unit/containers/course-section/resource-item/ResourceItem.spec.jsx
Comment (ShadowOfTheSpace) [inline tests/unit/containers/course-section/resource-item/ResourceItem.spec.jsx:1]: Remove changes from this file, they're unused

**Review by ShadowOfTheSpace — CHANGES_REQUESTED** [review]

**Review by ShadowOfTheSpace — APPROVED** [review]
