### PR TITLE
Replaced `useAxios` with `useQuery` on the My Cooperations page

### LINKED ISSUE #2997: Replace `useAxios` with `useQuery` on the My Cooperations page
**Description**
Replace the `useAxios` hook with a custom `useQuery` hook on the My Cooperations page to improve data fetching, caching, and error handling.

**Tasks**

1. Identify all instances of useAxios usage on the My Cooperations page.
2. Replace these instances with useQuery, ensuring proper integration with the existing components.
3. Implement appropriate query keys to differentiate and cache the data effectively.
4. Update the related test cases (if any) to accommodate the changes.
5. Ensure backward compatibility with any existing functionality.

**Expected Outcome**

- The data-fetching logic on the My Cooperations page utilizes useQuery.
- Enhanced data caching and better error handling.
- No regression in existing functionality.

**Additional Context**
Using `useQuery` will provide built-in caching, retries, and loading state management, simplifying the data-fetching logic and aligning with modern React development practices.

### PR DESCRIPTION
**Pull request by Made1ra**
Replaced the `useAxios` hook with a custom `useQuery` hook on the My Cooperations page to improve data fetching, caching, and error handling. Also, I did the same in the Active Students block because it uses the same service.

Screenshot 2025-01-01 at 18 09 40

Screenshot 2025-01-01 at 18 10 05

### CODE REVIEW

File: src/containers/my-cooperations/accept-cooperation-modal/AcceptCooperationModal.tsx
Comment (markgol777) [inline src/containers/my-cooperations/accept-cooperation-modal/AcceptCooperationModal.tsx:1]: Do we not have a Coorperation interface to replace the unkown with?

File: src/containers/my-cooperations/cooperations-container/CooperationContainer.tsx
Comment (markgol777) [inline src/containers/my-cooperations/cooperations-container/CooperationContainer.tsx:1]: same here

File: src/pages/my-cooperations/MyCooperations.tsx [hunk 1]
```diff
@@ -79,13 +76,13 @@ const MyCooperations = () => {
     [filters, page, itemsPerPage, sort]
   )
 
-  const {
-    loading,
-    response,
-    fetchData: getCooperations
-  } = useAxios({
-    service: getMyCooperations,
```
Comment (markgol777) [inline src/pages/my-cooperations/MyCooperations.tsx:87]: Why did you decide to remove the
getMyCoorperations function?
Also with the new PR you can finally use default response without any problems

File: src/pages/my-cooperations/MyCooperations.tsx [hunk 2]
```diff
@@ -133,20 +126,20 @@ const MyCooperations = () => {
...
+            getCooperations={refetch}
+            items={data?.items ?? []}
             showTable={showTable}
             sort={sortOptions}
           />
           <AppPagination
             onChange={handleChangePage}
             page={page}
-            pageCount={Math.ceil(response.count / itemsPerPage)}
+            pageCount={data?.count ? Math.ceil(data.count / itemsPerPage) : 0}
```
Comment (markgol777) [inline src/pages/my-cooperations/MyCooperations.tsx]: Replace the 0 with a 1 as the page can't start with a 0 but I'm not sure on this one 😓

**Review by markgol777 — CHANGES_REQUESTED** [review]

File: src/components/active-students/ActiveStudentsBlock.tsx [hunk 3]
```diff
@@ -23,13 +23,22 @@ const ActiveStudentsBlock = () => {
     []
   )
 
-  const { loading, response, error } = useAxios<ItemsWithCount<Cooperation>>({
-    service: getMyCooperations,
-    defaultResponse
+  const {
+    isLoading,
+    data = defaultResponse,
```
Comment (markgol777) [inline src/components/active-students/ActiveStudentsBlock.tsx]: We have intialData in our useQuery hook please don't use it this way

File: src/pages/my-cooperations/MyCooperations.tsx [hunk 4]
```diff
@@ -80,12 +83,12 @@ const MyCooperations = () => {
...
 
   const {
-    loading,
-    response,
-    fetchData: getCooperations
-  } = useAxios({
-    service: getMyCooperations,
-    defaultResponse
+    isLoading,
+    data = defaultResponse,
```
Comment (markgol777) [inline src/pages/my-cooperations/MyCooperations.tsx]: Same thing here please use intialData in useQuery options

File: src/pages/my-cooperations/MyCooperations.tsx [hunk 5]
```diff
@@ -80,12 +83,12 @@ const MyCooperations = () => {
...
+    refetch
+  } = useQuery<ItemsWithCount<Cooperation>>({
```
Comment (markgol777) [inline src/pages/my-cooperations/MyCooperations.tsx]: Also you don't have to specify the types anymore

File: src/components/active-students/ActiveStudentsBlock.tsx [hunk 6]
```diff
@@ -23,13 +23,22 @@ const ActiveStudentsBlock = () => {
...
+    error
+  } = useQuery<ItemsWithCount<Cooperation>>({
```
Comment (markgol777) [inline src/components/active-students/ActiveStudentsBlock.tsx]: Also you don't have to specify the types anymore

**Review by markgol777 — CHANGES_REQUESTED** [review]

File: src/components/active-students/ActiveStudentsBlock.tsx [hunk 7]
```diff
@@ -23,13 +22,21 @@ const ActiveStudentsBlock = () => {
...
+    }
   })
 
-  if (loading) return <Loader pageLoad size={50} />
-  if (error) return null
+  if (isLoading) {
+    return <Loader pageLoad size={50} />
+  }
+
+  if (error) {
```
Comment (markgol777) [inline src/components/active-students/ActiveStudentsBlock.tsx:37]:
```js
 if (loading) return <Loader pageLoad size={50} />
  if (error) return null
  ```

Why did you change it from this to the ones with {}?

**Review by markgol777 — CHANGES_REQUESTED** [review]

File: src/components/active-students/ActiveStudentsBlock.tsx (hunk 7 above)
Comment (Made1ra) [reply src/components/active-students/ActiveStudentsBlock.tsx:37]: It's more readable.

**Review by markgol777 — APPROVED** [review]

**Review by SofiiaYevush — APPROVED** [review]

**Review by ShadowOfTheSpace — APPROVED** [review]
