### PR TITLE
(SP: ) Fix choosing all resources on AddResourceModal #3119

### LINKED ISSUE #3119: (SP: ) Fix choosing all resources on AddResourceModal
Actual result: if we check = true on radio button all lessons checks, but near the Title this radio button is false. If we want to uncheck all lessons this function doesn`t work. 

**Check = true ( on radio button we don`t see that it is checked)**
Image

**Check = false (doesn`t work. Expected result: on radio button is checked is going to be false and all lessons beyond are going to be unchecked)**

Image

### PR DESCRIPTION
**Pull request by lizabre**
Fixed choosing all resources in 'Create course' page in 'Add resource' modal 

Before:

https://github.com/user-attachments/assets/eb79a272-37ab-4503-b499-2a63087d79e9

After:

https://github.com/user-attachments/assets/57f4204f-f68c-4266-a214-8a992066ce01

### CODE REVIEW

**Review by yur4uwe — APPROVED** [review]

**Review by uliaescha — APPROVED** [review]

File: src/containers/add-resources/AddResources.tsx [hunk 1]
```diff
@@ -88,16 +83,13 @@ const AddResources = <T extends CourseResource | Question>({
...
     (item: T) => {
-      setSelectedRows((selectedRows) =>
-        selectedRows.find((resource) => resource._id === item._id)
-          ? selectedRows.filter((resource) => resource._id !== item._id)
-          : [...selectedRows, item]
-      )
       handleSelectClick(item._id)
     },
-    [handleSelectClick]
+    [select]
```
Comment (Mike-Popovych) [inline src/containers/add-resources/AddResources.tsx]: image

**Review by Mike-Popovych — CHANGES_REQUESTED** [review]

File: src/containers/add-resources/AddResources.tsx (hunk 1 above)
Comment (lizabre) [reply src/containers/add-resources/AddResources.tsx]: Fixed it, thank you for noticing

File: src/containers/add-resources/AddResources.tsx [hunk 2]
```diff
@@ -154,7 +142,7 @@ const AddResources = <T extends CourseResource | Question>({
     sort: sortOptions,
     select,
     selectedRows,
```
Comment (Mike-Popovych) [inline src/containers/add-resources/AddResources.tsx:144]: Can we remove this selectedRows prop?

**Comment by Mike-Popovych** [comment]
image
image

File: src/components/enhanced-table/enhanced-table-head/EnhancedTableHead.tsx [hunk 3]
```diff
@@ -30,22 +30,22 @@ const EnhancedTableHead = <I extends TableItem>({
   columns,
   data,
   isSelection,
-  rowsPerPage,
```
Comment (Mike-Popovych) [inline src/components/enhanced-table/enhanced-table-head/EnhancedTableHead.tsx:33]: image
also remove this prop from interface

**Review by Mike-Popovych — CHANGES_REQUESTED** [review]

File: src/containers/add-resources/AddResources.tsx (hunk 2 above)
Comment (lizabre) [reply src/containers/add-resources/AddResources.tsx:144]: Yes, removed it in a new commit

File: src/components/enhanced-table/enhanced-table-head/EnhancedTableHead.tsx (hunk 3 above)
Comment (lizabre) [reply src/components/enhanced-table/enhanced-table-head/EnhancedTableHead.tsx:33]: Removed

**Review by IrynaKhylchuk — APPROVED** [review]

**Review by Mike-Popovych — APPROVED** [review]
