### PR TITLE
Fixed cooperation closing banner overlapping

### LINKED ISSUE #3309: (SP: 2) Cooperation Closing Banner Overlapping Notes Section
When the cooperation closing process has started, users see a related banner on the `Activities` page. Currently, when clicking the `Notes` button to open the notes section, the cooperation closing banner remains on top of the notes section, obstructing visibility.

Image

**Expected Behavior:**
The banner should shrink to the left, aligning with other content on the `Activities` page, ensuring the notes section is fully visible.

### PR DESCRIPTION
**Pull request by irynalaitaruk**
Fixed cooperation closing banner that overlapped notes section.
Before:
Screenshot 2025-04-08 at 23 40 17

After:
Screenshot 2025-04-08 at 23 39 20
Screenshot 2025-04-08 at 23 38 59

### CODE REVIEW

**Review by ArtemHolikov — APPROVED** [review]

**Review by Mike-Popovych — APPROVED** [review]

**Review by VKormylo — APPROVED** [review]

**Review by Mav-Ivan — APPROVED** [review]

File: src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx [hunk 1]
```diff
@@ -288,9 +288,12 @@ const CooperationDetails = () => {
...
         </Box>
       </Box>
-      {activeTab === CooperationTabsEnum.Activities && cooperationClosingModal}
       <Box sx={styles.notesBlock}>
-        <Box sx={styles.pageContent}>{pageContent()}</Box>
+        <Box sx={styles.pageContent}>
+          {activeTab === CooperationTabsEnum.Activities &&
+            cooperationClosingModal}
+          <Box sx={styles.pageContent}>{pageContent()}</Box>
+        </Box>
```
Comment (nebby2105) [inline src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx]: You dont need to wrap `pageContent()` in an extra Box because it's already inside a container with the correct styling
```suggestion
        <Box sx={styles.pageContent}>
          {activeTab === CooperationTabsEnum.Activities &&
            cooperationClosingModal}
          {pageContent()}
        </Box>
```

**Review by nebby2105 — CHANGES_REQUESTED** [review]

File: src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx (hunk 1 above)
Comment (irynalaitaruk) [reply src/containers/my-cooperations/cooperation-details/CooperationDetails.tsx]: I agree, committed

**Review by nebby2105 — APPROVED** [review]
