### PR TITLE
Fix a bug when selecting a level in offer filtering

### LINKED ISSUE #3306: Fix a bug when selecting a level in offer filtering
**It is impossible to select a level when filtering offers**

https://github.com/user-attachments/assets/37708b9f-d986-46c1-a4f8-c7c6ffb4a384

### PR DESCRIPTION
**Pull request by oleg191006**
Fixed a bug with the proficiency level filter in the "Find Offer" screen. Previously, selecting levels via checkboxes didn’t correctly update the filter state. Created a new handler function to manage checkbox changes properly and refactored related tests.

The previous implementation used a generic filter change handler that did not take into account the specific behavior of checkboxes, namely returning an array with a value. It expected a simple event or value, which caused the filter to receive incorrect or empty data when interacting with the checkbox.

https://github.com/user-attachments/assets/2c73b9a0-b5aa-4725-9e56-d51babc01dd7

### CODE REVIEW

**Review by ArtemHolikov — APPROVED** [review]

**Review by Mav-Ivan — APPROVED** [review]

**Comment by ShadowOfTheSpace** [comment]
I know this is unrelated to your issue, but on the video, I noticed that we have `Infinity` inside the `from` and `to` limits of the `Price` section. Can you look on that?

**Comment by oleg191006** [comment]
I see, I just tested it and noticed that infinity occurs when we have absolutely no offers for the skill level we chose. And I also noticed that during the first filtering attempt, precisely when selecting the beginner level, infinity also lights up, when you select the next times then everything displays normally

**Comment by oleg191006** [comment]
now there is an option to choose multiple levels instead of just one
https://github.com/user-attachments/assets/bf639480-f9ba-4195-b317-d405d2b83618

File: src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.tsx [hunk 1]
```diff
@@ -57,8 +57,11 @@ const OfferFilterList: FC<OfferFilterListProps> = ({
   const handleChecked = (_: SyntheticEvent<Element, Event>, checked: boolean) =>
     updateFiltersInQuery({ native: checked.toString() })
 
-  const handleFilterChange = (key: keyof FindOffersFilters) => () =>
-    updateFilterByKey(key)
+  const handleCheckboxChange =
+    (key: keyof FindOffersFilters) => (newValues: ProficiencyLevelEnum[]) => {
+      const cleanedValues = newValues.filter((v) => v)
```
Comment (Mike-Popovych) [inline src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.tsx]:
```suggestion
      const cleanedValues = newValues.filter((value) => value)
```

File: src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.tsx [hunk 2]
```diff
@@ -93,18 +96,19 @@ const OfferFilterList: FC<OfferFilterListProps> = ({
...
   return (
     <>
       {filterTitle(t('findOffers.filterTitles.level'))}
       <CheckboxList
         {...checkboxListProps}
         items={levelOptions}
-        onChange={handleFilterChange('proficiencyLevel')}
-        value={filters.proficiencyLevel}
+        onChange={handleCheckboxChange('proficiencyLevel')}
+        value={filters.proficiencyLevel || []}
```
Comment (Mike-Popovych) [inline src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.tsx]: image

**Review by Mike-Popovych — CHANGES_REQUESTED** [review]

**Review by Mike-Popovych — APPROVED** [review]
