### PR TITLE
Fixed errors in EnrollOffer container

### LINKED ISSUE #3268: (SP:) Fix errors in `EnrollOffer` container
Fix occured errors in EnrollOffer container

Path:
Image

Code:
Image

Image

Errors:
Image

### PR DESCRIPTION
**Pull request by uliaescha**
Fixed errors in EnrollOffer container

image
image

- Made additionalInfo optional in EnrollOfferForm interface.  
- Updated validateAdditionalInfo to handle undefined values.

image
image

Sending the request with an empty additionalInfo
image

### CODE REVIEW

**Comment by VKormylo** [comment]
Did you check whether the request is sent without additionalInfo if it is empty? If it's working as expected then great.

**Comment by Mike-Popovych** [comment]
image

If you submit the form with an empty additionalInfo, an error occurs.

**Comment by uliaescha** [comment]
Fixed that issue

**Comment by uliaescha** [comment]
> image
> 
> If you submit the form with an empty additionalInfo, an error occurs.

Fix that issue already

File: src/containers/offer-details/enroll-offer/EnrollOffer.tsx [hunk 1]
```diff
@@ -72,13 +72,14 @@ const EnrollOffer: React.FC<EnrollOfferProps> = ({ offer, enrollOffer }) => {
     onSuccess: handleResponse
   })
 
-  const validateAdditionalInfo = (additionalInfoValue: string) => {
+  const validateAdditionalInfo = (additionalInfoValue: string | undefined) => {
+    if (additionalInfoValue === undefined) {
+      return
+    }
```
Comment (Mike-Popovych) [inline src/containers/offer-details/enroll-offer/EnrollOffer.tsx]:
```suggestion
  const validateAdditionalInfo = (additionalInfoValue: string | undefined) => {
    const validate = textField(30, 1000)
    
    if (!additionalInfoValue) {
      delete data.additionalInfo
      return
    }

    return validate(additionalInfoValue)
  }
```

**Review by Mike-Popovych — APPROVED** [review]

**Review by SofiiaYevush — APPROVED** [review]

**Review by ArtemHolikov — APPROVED** [review]
