### PR TITLE
Rewrote AddPhotoStep to tsx format and fix the sonar issues

### LINKED ISSUE #2197: (SP: 1) Rewrite AddPhotoStep to tsx format and fix the sonar issues
image
image

### PR DESCRIPTION
**Pull request by YulichkaR**
Sonar Issue:
image

AddPhotoStep:
image

### CODE REVIEW

**Review by ipasic-softserve — APPROVED** [review]

**Review by dudchakk — APPROVED** [review]

File: src/containers/tutor-home-page/add-photo-step/AddPhotoStep.tsx [hunk 1]
```diff
@@ -0,0 +1,102 @@
+import { useState } from 'react'
+import { useTranslation } from 'react-i18next'
+import { Box, Typography } from '@mui/material'
+
+import FileUploader from '~/components/file-uploader/FileUploader'
+import DragAndDrop from '~/components/drag-and-drop/DragAndDrop'
+import { imageResize } from '~/utils/image-resize'
+
+import { style } from '~/containers/tutor-home-page/add-photo-step/AddPhotoStep.style'
+import { useStepContext } from '~/context/step-context'
```
Comment (abalanovsky) [inline src/containers/tutor-home-page/add-photo-step/AddPhotoStep.tsx:10]: organize imports please:
-libs,
-containers ,contexts, services, hooks, components
-utils, routes, const, types, styles

File: src/containers/tutor-home-page/add-photo-step/AddPhotoStep.tsx [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+import useBreakpoints from '~/hooks/use-breakpoints'
+import { validationData } from './constants'
+
+interface AddPhotoStepProps {
+  btnsBox: React.ReactNode
```
Comment (abalanovsky) [inline src/containers/tutor-home-page/add-photo-step/AddPhotoStep.tsx:15]: try to avoid words shorten

**Review by abalanovsky — APPROVED** [review]

**Review by Mike-Popovych — APPROVED** [review]

**Review by YaroslavChuiko — APPROVED** [review]
