### PR TITLE
Fixed updating offer count when creating new offer in CompleteProfileBlock

### LINKED ISSUE #2606: (SP: 2) Fix updating offer data in CompleteProfileBlock
Fix this bug:
- [x] Offer ProfileItem is only updated when user creates new offer **and refreshes the page**: is noticable in PR #2605

### PR DESCRIPTION
**Pull request by dudchakk**
**How it works now:**

https://github.com/user-attachments/assets/153e0a9d-53b1-4b1d-8f64-ff4b0955a508

### CODE REVIEW

**Review by BohdanMylyi — APPROVED** [review]
👍

File: src/components/complete-profile/CompleteProfileBlock.tsx [hunk 1]
```diff
@@ -53,7 +60,7 @@ const CompleteProfileBlock: FC<CompleteProfileBlockProps> = ({
       OfferService.getUsersOffers({
```
Comment (PavloDolia) [inline src/components/complete-profile/CompleteProfileBlock.tsx]: you don't have to use the useCallback hook at all, you can pass the `OfferService.getUsersOffers` function to the useAxios hook, or at least you should delete `isOfferCreated` from the dependancy array.

File: src/components/complete-profile/CompleteProfileBlock.tsx [hunk 2]
```diff
@@ -42,6 +45,10 @@ const CompleteProfileBlock: FC<CompleteProfileBlockProps> = ({
   const homePage = useMatch(guestRoutes[userRole as UserRole].path)
   const [isOpen, setIsOpen] = useState(false)
 
+  const { openDrawer, closeDrawer, isOpen: isDrawerOpen } = useDrawer()
+  const [isOfferCreated, setIsOfferCreated] = useState(false)
+  const handleOpenDrawer = () => openDrawer()
```
Comment (PavloDolia) [inline src/components/complete-profile/CompleteProfileBlock.tsx]: why did you create `handleOpenDrawer` function? You don' have to do it, and the `handleOpenDrawer` function will be recreated after each render, which can affect productivity. As far as I understand you want to rename the `openDrawer` function, so you could destructure with a renaming, like in [this example](https://stackoverflow.com/questions/57065348/destructuring-and-rename-property)

File: src/components/profile-item/ProfileItem.tsx [hunk 3]
```diff
@@ -8,29 +8,25 @@ import { styles } from '~/components/profile-item/ProfileItem.styles'
...
   userRole: UserRoleEnum | ''
+  handleOpenDrawer?: () => void | undefined
 }
 
 const ProfileItem = ({
   item,
   userRole,
-  isFilled = false
+  isFilled = false,
+  handleOpenDrawer = undefined
```
Comment (PavloDolia) [inline src/components/profile-item/ProfileItem.tsx]: we don't have to set `undefined` as a default value for an object property, because it will be `undefined` if the object doesn't contain a property

File: src/containers/offer-page/create-offer/CreateOffer.tsx [hunk 4]
```diff
@@ -8,16 +8,26 @@ import { CreateOrUpdateOfferData } from '~/types'
 
 interface CreateOfferProps {
   closeDrawer: () => void
+  updateOffer?: Dispatch<SetStateAction<boolean>>
 }
 
-const CreateOffer: FC<CreateOfferProps> = ({ closeDrawer }) => {
+const CreateOffer: FC<CreateOfferProps> = ({
+  closeDrawer,
+  updateOffer = undefined
```
Comment (PavloDolia) [inline src/containers/offer-page/create-offer/CreateOffer.tsx]: don't need to set a property to `undefined` here

File: src/containers/offer-page/create-or-edit-offer/CreateOrEditOffer.tsx [hunk 5]
```diff
@@ -38,15 +38,17 @@ import { openAlert } from '~/redux/features/snackbarSlice'
...
   service: ServiceFunction<Offer | null, CreateOrUpdateOfferData>
+  updateOffer?: Dispatch<SetStateAction<boolean>>
 }
 
 const CreateOrEditOffer: FC<CreateOrUpdateOfferProps> = ({
   existingOffer = null,
   closeDrawer,
-  service
+  service,
+  updateOffer = undefined
```
Comment (PavloDolia) [inline src/containers/offer-page/create-or-edit-offer/CreateOrEditOffer.tsx]: `undefined` isn't needed

**Review by PavloDolia — CHANGES_REQUESTED** [review]

File: src/components/complete-profile/CompleteProfileBlock.tsx (hunk 2 above)
Comment (dudchakk) [reply src/components/complete-profile/CompleteProfileBlock.tsx]: I created this function following the example at the MyOffers.tsx component. But looks like you are right, I’ll try to remove it

File: src/components/complete-profile/CompleteProfileBlock.tsx (hunk 1 above)
Comment (dudchakk) [reply src/components/complete-profile/CompleteProfileBlock.tsx]: I use isOfferCreated dependency because it makes the hook re-send request to get user offers when the new offer is created in CompleteProfileBlock. It was the main task) without this dependency the first created offer won’t be shown in CompleteProfileBlock unless the user refreshes the page

Comment (PavloDolia) [reply src/components/complete-profile/CompleteProfileBlock.tsx:59]: ok, now I understand your idea, but we should use the `useEffect` hook for such purposes because it will make code much more readable

**Review by PavloDolia — CHANGES_REQUESTED** [review]

File: src/components/complete-profile/CompleteProfileBlock.tsx (hunk 1 above)
Comment (PavloDolia) [reply src/components/complete-profile/CompleteProfileBlock.tsx]: ok, now I understand your idea, but we should use the `useEffect` hook if you want to re-send request because it will make code much more readable

**Review by PavloDolia — APPROVED** [review]

**Review by ipasic-softserve — APPROVED** [review]

**Review by Mav-Ivan — APPROVED** [review]
