### PR TITLE
Fixed drag-and-drop functionality and unique ID generation

### LINKED ISSUE #2381: (SP: 3) Drag and Drop functionality and unique ID generation issues
### Drag and Drop functionality and unique ID generation issues
The drag and drop functionality for rearranging sections in `Courses` and `Cooperations` is not working properly. Additionally, when a course or cooperation has more than two sections, the generated IDs are not unique, causing issues when deleting sections. Deleting one section can lead to the deletion of all sections within the course or cooperation. 
The implemented changes need to handle the unique IDs properly and update the order of sections correctly.

- [ ] Fix implementation of the drag and drop functionality for rearranging sections in `Course`:
Screenshot 2024-08-22 at 17 46 24

#

- [ ] Fix implementation of the drag and drop functionality for rearranging sections in `Cooperation`:
cooperation section id

#

- [ ] Fix issue with deleting one of sections that cause deleting all sections in `Course` and `Cooperation`.
cooperation section deleting

#

- [ ] Ensure that unique IDs are assigned to each section, even when there are multiple sections within a `Course` or `Cooperation`. (Ensure that the ID is assigned to each section when it's **created** and **updated** when necessary)

#

- [ ] Fix the **issue where the same unique 'key' is assigned to each child in the list during edit mode** of `Cooperation`. This causes the screen to freeze and prevents the ability to change the order of sections, delete, or access other functionality that should be enabled:
Screenshot 2024-08-24 at 00 19 26

### PR DESCRIPTION
**Pull request by Olenka-Hryk**
## Fixed drag-and-drop functionality and unique ID generation issues [ Close #2381 ]
The drag-and-drop functionality for rearranging sections in `Courses` and `Cooperations` is now working properly. Additionally, when a course or cooperation has more than two sections, the generated IDs are unique, which resolves the issue where deleting one section would lead to the deletion of all sections within the course or cooperation
 
The implemented changes now properly handle unique IDs and correctly update the order of sections.
Screenshot 2024-08-25 at 17 49 11

- [x] Fixed implementation of the drag and drop functionality for rearranging sections in `Course`:
Screenshot 2024-08-22 at 17 46 24

#

- [x] Fixed implementation of the drag and drop functionality for rearranging sections in `Cooperation`:
cooperation section id

#

- [x] Fixed issue with deleting one of the sections that cause deleting all sections in `Course` and `Cooperation`.
cooperation section deleting

#

- [x] Ensured that unique IDs are assigned to each section, even when there are multiple sections within a `Course` or `Cooperation`. Specifically, the ID is assigned to each section when it is **created** and **updated** as necessary.

#

- [x] Fixed the **issue where the same unique 'key' is assigned to each child in the list during edit mode** of `Cooperation`. This fix prevents the screen from freezing and ensures that users can change the order of sections, delete them, or access other functionality as intended.
Screenshot 2024-08-24 at 00 19 26

#### Additionally, I rewrote the spec for `CooperationActivitiesList.tsx` container to up the coverage: 
_Coverage before changes_:
Screenshot 2024-07-29 at 20 11 16

_Current Test Coverage:_
Screenshot 2024-08-24 at 17 58 12

### CODE REVIEW

File: src/components/cooperation-section-view/CooperationSectionView.tsx [hunk 1]
```diff
@@ -36,15 +36,15 @@ const CooperationSectionView: FC<CooperationSectionViewProps> = ({
   )
 
   return (
-    <Box sx={styles.root}>
+    <Box key={id} sx={styles.root}>
```
Comment (YaroslavChuiko) [inline src/components/cooperation-section-view/CooperationSectionView.tsx:39]: Why do we need this `key` prop here?

**Review by YaroslavChuiko — APPROVED** [review]

File: src/components/cooperation-section-view/CooperationSectionView.tsx (hunk 1 above)
Comment (Olenka-Hryk) [reply src/components/cooperation-section-view/CooperationSectionView.tsx:39]: Fixed in PR #2392. [CooperationSectionView.tsx](https://github.com/ita-social-projects/SpaceToStudy-Client/blob/e2311d4d43a0a766c187c3a8ea102bb58a06999b/src/components/cooperation-section-view/CooperationSectionView.tsx)

**Review by docia — APPROVED** [review]

**Review by Mike-Popovych — APPROVED** [review]
