### PR TITLE
Fixed using array index as key in lists

### LINKED ISSUE #2677: (SP: 0.5) Avoid Using Array Index as Key in JSX Lists
### **Description:**  
Using array indices as keys in list components can cause unexpected behavior, especially when items are reordered or changed. Instead, use a unique ID for each item to help React handle updates more efficiently.

### **File Affected:**  
`AddProfessionalCategoryModal.tsx`

### PR DESCRIPTION
**Pull request by Made1ra**
Description:
Using array indices as keys in list components can cause unexpected behavior, especially when items are reordered or changed. Instead, use a unique ID for each item to help React handle updates more efficiently.

File Affected:
AddProfessionalCategoryModal.tsx

### CODE REVIEW

File: src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx [hunk 1]
```diff
@@ -214,7 +214,7 @@ const AddProfessionalCategoryModal: FC<AddProfessionalCategoryModalProps> = ({
       disableOptions={data.subjects as Array<Partial<SubjectInterface>>}
       handleChange={handleProfessionalSubjectChange(index)}
       handleSubjectDelete={() => handleSubjectDelete(subject._id || '')}
-      key={index}
+      key={subject._id || crypto.randomUUID()}
```
Comment (ShadowOfTheSpace) [inline src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx]: Is there any chance for `_id` here to be falsable?

Comment (Made1ra) [reply src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx]: Yes, sometimes it's just an empty string.

Comment (ipasic-softserve) [reply src/containers/edit-profile/professional-info-tab/add-professional-category-modal/AddProfessionalCategoryModal.tsx]: I think we can remove `crypto.randomUUID()`, since `id=''` will only be used once, when no category has been selected yet.

**Review by ipasic-softserve — APPROVED** [review]

**Review by Renatavl — APPROVED** [review]

**Review by Mike-Popovych — APPROVED** [review]
