### PR TITLE
Fix active students block with no active cooperations

### LINKED ISSUE #2575: (SP: ) Align active students block with figma
Currently, if the tutor has no students, the `ActiveStudents` block will not render. Instead, it should display a message indicating that the tutor has no students and include an `add student` button according to the figma [mockup](https://www.figma.com/design/liJZDYhUnDP15Pi9bipDcv/Space2Study-(Students)?node-id=2140-56000&t=tzu64Mx870EGSd4k-4).

image

### PR DESCRIPTION
**Pull request by ipasic-softserve**
https://github.com/user-attachments/assets/5f1ae449-0636-4519-b3ea-0734acf75008

### CODE REVIEW

**Review by PavloDolia — APPROVED** [review]

File: src/components/active-students/ActiveStudentsBlock.tsx [hunk 1]
```diff
@@ -29,7 +29,37 @@ const ActiveStudentsBlock = () => {
...
+          <Typography sx={styles.title}>
+            {t('activeStudents.noStudentsYet')}
+          </Typography>
+          <Box
+            data-testid='addStudent'
+            onClick={onAddStudentClick}
+            sx={styles.showMoreWrapper}
+          >
+            <AppIconButton size='medium' sx={styles.showMoreButton}>
+              <MoreHoriz />
```
Comment (YaroslavChuiko) [inline src/components/active-students/ActiveStudentsBlock.tsx]: it seems here should be another icon (Add)

**Review by YaroslavChuiko — APPROVED** [review]

**Review by BohdanMylyi — APPROVED** [review]
