### PR TITLE
Fixed the ability to save answer of question when type is Open Answer

### LINKED ISSUE #3146: (SP: ) Fix the ability to save answer of question when type is Open Answer
Image

Image

Image

Tasks:

- Fix the ability to save answer in response
- Add answer view in Edit Quiz page
- Verify that on CooperationActivities page answer validate correctly

### PR DESCRIPTION
**Pull request by amoutens**
- Fixed ability to save Open Answer answers
- Provided opportunity to add more than one answer for Open Answer
- Added styles for edit open answer question
- Added error handling on blur when we input empty new value
- Provided functional and styles for checking right answer when Open Answer 

image
image
image
image
image

### CODE REVIEW

File: src/components/question-editor/QuestionEditor.tsx [hunk 1]
```diff
@@ -114,17 +121,17 @@ const QuestionEditor: FC<QuestionEditorProps> = ({
...
-    }
+    if (isEmptyAnswer) return
+
+    handleNonInputValueChange('answers', [
+      ...data.answers,
+      {
+        id: data.answers.length,
+        text: '',
+        isCorrect: isOpenAnswer,
+        isEditing: isOpenAnswer || undefined
```
Comment (ShadowOfTheSpace) [inline src/components/question-editor/QuestionEditor.tsx]: What do you mean here? `isEditing` should have default value of undefined, or it's boolean and should be false, when `isOpenAnswer` is falsy?

File: src/components/question-editor/QuestionEditor.tsx [hunk 2]
```diff
@@ -178,7 +210,18 @@ const QuestionEditor: FC<QuestionEditorProps> = ({
...
+    const { text } = updatedAnswers[index]
+
+    if (text.trim()) {
+      updatedAnswers[index].isEditing = false
+      handleNonInputValueChange('answers', updatedAnswers)
+    } else {
+      handleErrors('answers', validateOpenAnswer(text))
+    }
+  }
+  const isButtonVisible = text
```
Comment (ShadowOfTheSpace) [inline src/components/question-editor/QuestionEditor.tsx]:
```suggestion
  const isButtonVisible = Boolean(text)
```

File: src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx [hunk 3]
```diff
@@ -1,11 +1,4 @@
-import {
-  useCallback,
-  FC,
-  useState,
-  useEffect,
-  Dispatch,
-  SetStateAction
-} from 'react'
+import React from 'react'
```
Comment (ShadowOfTheSpace) [inline src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx]: You don't need to import React here for types. Just write React.FC and all will be fine

File: src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx [hunk 4]
```diff
@@ -32,25 +25,25 @@ import { getErrorKey } from '~/utils/get-error-key'
...
   const { openModal, closeModal } = useModalContext()
 
-  const createQuestionService = useCallback(
+  const createQuestionService = React.useCallback(
     (data?: QuestionForm) => ResourceService.createQuestion(data),
     []
   )
 
-  const updateQuestionService = useCallback(
+  const updateQuestionService = React.useCallback(
```
Comment (ShadowOfTheSpace) [inline src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx]: Please, import it. We are using React namespace only for types.

File: src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx [hunk 5]
```diff
@@ -147,15 +164,17 @@ const CreateOrEditQuizQuestion: FC<CreateOrEditQuizQuestionProps> = ({
     })
   }
 
-  useEffect(() => {
+  React.useEffect(() => {
```
Comment (ShadowOfTheSpace) [inline src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx]: Same here, please

File: src/containers/quiz/quiz-question/Question.tsx [hunk 6]
```diff
@@ -64,7 +64,7 @@ const QuizQuestion: FC<QuizQuestionProps> = ({
     shouldShowAnswersCorrectness &&
     (isCorrect ? <CheckIcon sx={iconStyles} /> : <CloseIcon sx={iconStyles} />)
 
-  const showCorrectAnswers = shouldShowCorrectAnswers && !isOpenAnswer
+  const showCorrectAnswers = shouldShowCorrectAnswers
```
Comment (ShadowOfTheSpace) [inline src/containers/quiz/quiz-question/Question.tsx]: Why you can't use `shouldShowCorrectAnswers` later? why you need another variable for that?

File: src/containers/quiz/quiz-question/Question.tsx [hunk 7]
```diff
@@ -135,7 +135,7 @@ const QuizQuestion: FC<QuizQuestionProps> = ({
 
   const answersBlock = isOpenAnswer ? (
     <Answer
-      isCorrect
+      isCorrect={isCorrect}
```
Comment (ShadowOfTheSpace) [inline src/containers/quiz/quiz-question/Question.tsx:136]: Why you did that? It's a sonar issue

File: src/containers/quiz/quiz-question/Question.tsx [hunk 8]
```diff
@@ -135,7 +135,7 @@ const QuizQuestion: FC<QuizQuestionProps> = ({
...
       isEditable={isEditable}
```
Comment (ShadowOfTheSpace) [inline src/containers/quiz/quiz-question/Question.tsx:137]: Use the shortest form for boolean props
```suggestion
      isEditable
```

File: tests/unit/containers/my-quizzes/CreateOrEditQuizQuestion.spec.jsx [hunk 9]
```diff
@@ -26,6 +26,19 @@ const mockedQuestion = {
     name: 'Category name'
   }
 }
+const mockedOpenAnswerQuestion = {
+  title: 'Question title',
+  text: 'Question text',
+  answers: [
+    {id: 0, text: 'Answer 1', isCorrect: true },
```
Comment (ShadowOfTheSpace) [inline tests/unit/containers/my-quizzes/CreateOrEditQuizQuestion.spec.jsx]: Format this line, please

File: tests/unit/containers/my-quizzes/CreateOrEditQuizQuestion.spec.jsx [hunk 10]
```diff
@@ -116,6 +129,55 @@ describe('CreateOrEditQuizQuestion component without question', () => {
...
+
+    const addNewAnswerBtn = screen.getByTestId('addNewAnswerBtn')
+    fireEvent.click(addNewAnswerBtn)
+
+    const saveBtn = screen.getByText('common.save')
+    fireEvent.click(saveBtn)
+
+    await waitFor(() => {
+      expect(createQuestionSpy).toHaveBeenCalledWith(
+        expect.objectContaining({
```
Comment (ShadowOfTheSpace) [inline tests/unit/containers/my-quizzes/CreateOrEditQuizQuestion.spec.jsx]: function should be called with `expect`? Are you sure about this?

File: src/components/question-editor/QuestionEditor.tsx [hunk 11]
```diff
@@ -216,36 +257,32 @@ const QuestionEditor: FC<QuestionEditorProps> = ({
...
+        data-testid='addNewAnswerBtn'
+        onClick={addNewOneAnswer}
+        sx={
+          isOpenAnswer
+            ? spliceSx(styles.addRadio(isEmptyAnswer), styles.openAnswer)
+            : styles.addRadio(isEmptyAnswer)
+        }
+      >
+        {isOpenAnswer ? (
+          <Typography color={isEmptyAnswer ? 'primary.300' : ''}>
```
Comment (ShadowOfTheSpace) [inline src/components/question-editor/QuestionEditor.tsx]: Is `color = ''` exists?
```suggestion
          <Typography color={isEmptyAnswer ? 'primary.300' : undefined}>
```

**Review by ShadowOfTheSpace — CHANGES_REQUESTED** [review]

File: src/components/question-editor/QuestionEditor.tsx (hunk 1 above)
Comment (amoutens) [reply src/components/question-editor/QuestionEditor.tsx]: Firstly I made that the default value should be undefined, but after your comment I checked and it works with only `isOpenAnswer` statement

File: src/containers/quiz/quiz-question/Question.tsx (hunk 6 above)
Comment (amoutens) [reply src/containers/quiz/quiz-question/Question.tsx]: Sorry, also didn't noticed

File: src/containers/quiz/quiz-question/Question.tsx (hunk 7 above)
Comment (ShadowOfTheSpace) [reply src/containers/quiz/quiz-question/Question.tsx:136]: Sorry, it's was my bad - if you have boolean state for that prop (that can be `true` or `false`), you should `isCorrect={isCorrect}`. If it is just `true` value - use the shortest form (`isCorrect` instead of `isCorrect={true}`)

File: src/containers/quiz/quiz-question/Question.tsx (hunk 8 above)
Comment (ShadowOfTheSpace) [reply src/containers/quiz/quiz-question/Question.tsx:137]: Same as in previous comment, sorry)

File: src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx [hunk 12]
```diff
@@ -150,12 +161,14 @@ const CreateOrEditQuizQuestion: FC<CreateOrEditQuizQuestionProps> = ({
   useEffect(() => {
     !question && onOpenCreateQuestionModal()
     // eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (markgol777) [inline src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx]: Let's try to not use eslint disablers in our project

File: src/types/questions/interfaces/questions.interface.ts [hunk 13]
```diff
@@ -37,6 +37,7 @@ export interface UpdateQuestionParams {
 
 export interface QuestionFormAnswer extends Answer {
   id: number
+  isEditing?: boolean
```
Comment (markgol777) [inline src/types/questions/interfaces/questions.interface.ts:40]: Why isEditing optional?

**Review by markgol777 — CHANGES_REQUESTED** [review]

**Comment by markgol777** [comment]
image

Regarding this. This is so called `varenychky` or `gastronomy` just rerun the tests and they should work.

Perhaps your coverage will go up too

File: src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx (hunk 12 above)
Comment (amoutens) [reply src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx]: it isn't mine

File: src/types/questions/interfaces/questions.interface.ts (hunk 13 above)
Comment (amoutens) [reply src/types/questions/interfaces/questions.interface.ts:40]: because isEditing only exists on openAnswer question type

**Comment by amoutens** [comment]
> image
> 
> Regarding this. This is so called `varenychky` or `gastronomy` just rerun the tests and they should work.
> 
> Perhaps your coverage will go up too

Thanks, I'll try. I'm going to fix some comments and then push again

File: src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx (hunk 12 above)
Comment (markgol777) [reply src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx]: Yes, but If you're working on the pr you should fix all of the issues coming with it. In my opinion at least...

File: src/types/questions/interfaces/questions.interface.ts (hunk 13 above)
Comment (markgol777) [reply src/types/questions/interfaces/questions.interface.ts:40]: okay then perhaps should we make 2 different types? up 2 u tho

Comment (amoutens) [reply src/types/questions/interfaces/questions.interface.ts:40]: thanks, I'll take a look

**Comment by markgol777** [comment]
> > image
> > Regarding this. This is so called `varenychky` or `gastronomy` just rerun the tests and they should work.
> > Perhaps your coverage will go up too
> 
> Thanks, I'll try. I'm going to fix some comments and then push again

image

It's just enough to push this button but alright

File: src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx (hunk 12 above)
Comment (amoutens) [reply src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx]: I'll try to do my best

Comment (ShadowOfTheSpace) [reply src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx]: Just add `useCallback` to the `onOpenCreateQuestionModal` function declaration. This will stabilize the reference for that function, and `useEffect` will run only if `question` or `onOpenCreateQuestionModal` are changed.

File: tests/unit/containers/my-quizzes/CreateOrEditQuizQuestion.spec.jsx (hunk 10 above)
Comment (amoutens) [reply tests/unit/containers/my-quizzes/CreateOrEditQuizQuestion.spec.jsx]: Yes, it is correct approach in functions. This expect allows you to verify that our function was called with an object that partially matches your expectations, rather than requiring an exact match. But I can remove it, it isn't necessary there

File: src/types/questions/interfaces/questions.interface.ts (hunk 13 above)
Comment (amoutens) [reply src/types/questions/interfaces/questions.interface.ts:40]: I decided to leave as it was because creating 2 different types brings a lot of types mismatches

File: tests/unit/containers/my-quizzes/CreateOrEditQuizQuestion.spec.jsx (hunk 10 above)
Comment (ShadowOfTheSpace) [reply tests/unit/containers/my-quizzes/CreateOrEditQuizQuestion.spec.jsx]: Got it!

File: src/components/question-editor/QuestionEditor.tsx [hunk 14]
```diff
@@ -114,17 +121,17 @@ const QuestionEditor: FC<QuestionEditorProps> = ({
...
-        ...data.answers,
-        {
-          id: data.answers.length,
-          text: '',
-          isCorrect: false
-        }
-      ]
-      handleNonInputValueChange('answers', addAnswer)
-    }
+    if (isEmptyAnswer) return
```
Comment (ShadowOfTheSpace) [inline src/components/question-editor/QuestionEditor.tsx]: Add braces here, please

File: src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx [hunk 15]
```diff
@@ -145,17 +159,20 @@ const CreateOrEditQuizQuestion: FC<CreateOrEditQuizQuestionProps> = ({
...
+  }, [openModal, onCloseCreation, onOpenCreation, data, onCancel])
+
+  const onOpenCreateQuestionModalRef = useRef(onOpenCreateQuestionModal)
 
   useEffect(() => {
-    !question && onOpenCreateQuestionModal()
-    // eslint-disable-next-line react-hooks/exhaustive-deps
-  }, [])
+    !question && onOpenCreateQuestionModalRef.current()
+  }, [question])
```
Comment (ShadowOfTheSpace) [inline src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx]: Very strange usage of `useRef`
Check, please, how it workds without `useRef`, but with `onOpenCreateQuestionModal` inside dependency array

File: tests/unit/components/question-editor/QuestionEditor.spec.jsx
Comment (ShadowOfTheSpace) [inline tests/unit/components/question-editor/QuestionEditor.spec.jsx:1]: Format this file, please

File: tests/unit/components/question-editor/QuestionEditor.spec.jsx [hunk 16]
```diff
@@ -78,19 +80,18 @@ describe('QuestionEditor component with an open question type', () => {
...
-    fireEvent.change(answerInput, {
-      target: { value: 'New answer' }
-    })
-
-    expect(handleInputChange).toHaveBeenCalled()
+    const addNewOneButton = screen.getByTestId('addNewAnswerBtn')
+    fireEvent.click(addNewOneButton)
+    
+    expect(handleNonInputValueChange).toHaveBeenCalledWith("answers", [
+      { id: 0, text: "", isCorrect: true, isEditing: true },
```
Comment (ShadowOfTheSpace) [inline tests/unit/components/question-editor/QuestionEditor.spec.jsx]:
```suggestion
      { id: 0, text: '', isCorrect: true, isEditing: true },
```

File: tests/unit/containers/my-quizzes/CreateOrEditQuizQuestion.spec.jsx
Comment (ShadowOfTheSpace) [inline tests/unit/containers/my-quizzes/CreateOrEditQuizQuestion.spec.jsx:1]: Don't forget to format this file with prettier

File: tests/unit/containers/my-quizzes/CreateOrEditQuizQuestion.spec.jsx [hunk 17]
```diff
@@ -116,6 +129,37 @@ describe('CreateOrEditQuizQuestion component without question', () => {
     expect(snackbar).toBeInTheDocument()
     expect(createQuestionSpy).toHaveBeenCalled()
   })
+  it('should call onCreateQuestion with openAnswer data', async () => {
+    mockAxiosClient
+      .onPost(`${URLs.resources.questions.post}`)
```
Comment (ShadowOfTheSpace) [inline tests/unit/containers/my-quizzes/CreateOrEditQuizQuestion.spec.jsx]:
```suggestion
      .onPost(URLs.resources.questions.post)
```

File: tests/unit/containers/quiz/QuizQuestion.spec.jsx [hunk 18]
```diff
@@ -38,4 +38,24 @@ describe('Quiz Question tests', () => {
     const element = screen.getByText('0/1')
     expect(element).toBeInTheDocument()
   })
+  it('Should render correctness icon if shouldShowAnswersCorrectness is true', () => {
```
Comment (ShadowOfTheSpace) [inline tests/unit/containers/quiz/QuizQuestion.spec.jsx]:
```suggestion
  it('should render correctness icon if shouldShowAnswersCorrectness is true', () => {
```

File: tests/unit/containers/quiz/QuizQuestion.spec.jsx [hunk 19]
```diff
@@ -38,4 +38,24 @@ describe('Quiz Question tests', () => {
...
+    renderWithProps({ shouldShowAnswersCorrectness: true, value: 'Correct answer' })
+
+    const icon = screen.getAllByTestId('CheckIcon')[0]
+    expect(icon).toBeInTheDocument()
+  })
+  it('Should render open answer input field', () => {
```
Comment (ShadowOfTheSpace) [inline tests/unit/containers/quiz/QuizQuestion.spec.jsx]:
```suggestion
  it('should render open answer input field', () => {
```

**Review by ShadowOfTheSpace — CHANGES_REQUESTED** [review]

File: src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx (hunk 15 above)
Comment (amoutens) [reply src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx]: If we put onOpenCreateQuestionModel, it does'nt work

Comment (ShadowOfTheSpace) [reply src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx]: I checked this problem on your branch.
It's a really complicated one and demands a lot of refactoring of those components.

Firstly, you need to change the behavior of opening the `CreateOrEditQuestionModal` modal (currently it opens inside `useEffect`). 
Modal should open inside `onClick` callback to both buttons (edit and create), not inside `useEffect`.

Check `useImperativeHandle` hook from React, it will help.
You should wrap the `CreateOrEditQuizQuestion` component with `forwardRef`, provide a callback that should be called for `useImperativeHandle` that opens the modal and use a reference for this component (`CreateOrEditQuizQuestion`) to open the modal on button click.

Comment (amoutens) [reply src/containers/my-quizzes/create-or-edit-quiz-question/CreateOrEditQuizQuestion.tsx]: This fix does not apply to the current issue at all, so it is better, to my mind, to leave this statement as it was before any changes in this branch and create a separate ticket for the fix, because it happens quite often in our project

`// eslint-disable-next-line react-hooks/exhaustive-deps`

File: tests/unit/components/question-editor/QuestionEditor.spec.jsx [hunk 20]
```diff
@@ -78,19 +80,23 @@ describe('QuestionEditor component with an open question type', () => {
...
 
-    fireEvent.change(answerInput, {
-      target: { value: 'New answer' }
-    })
-
-    expect(handleInputChange).toHaveBeenCalled()
+    const addNewOneButton = screen.getByTestId('addNewAnswerBtn')
+    fireEvent.click(addNewOneButton)
+    
+    expect(handleNonInputValueChange).toHaveBeenCalledWith("answers", [
```
Comment (ShadowOfTheSpace) [inline tests/unit/components/question-editor/QuestionEditor.spec.jsx]:
```suggestion
    expect(handleNonInputValueChange).toHaveBeenCalledWith('answers', [
```

**Review by ShadowOfTheSpace — APPROVED** [review]
Approved, but don't forget to format files with prettier

**Review by Mike-Popovych — APPROVED** [review]

**Review by markgol777 — APPROVED** [review]
