### PR TITLE
Fixed error in editProfileSlice

### LINKED ISSUE #3284: (SP: 1) Fix error in editProfileSlice
Fix error in editProfileSlice

Path:
Image

Code:
Image

Error:
Image

### PR DESCRIPTION
**Pull request by SofiiaYevush**
- Removed `response.data` return. Now `updateUser` service returns void (no data expected from PATCH requests), so we simply await completion.
- Explicit `return true` on success. Replaced unsafe type-ignored returns with a clear success flag for better intent and type safety.
- Updated endpoint and service.
- Updated test.

Examples of successful updating of the data:
image

image

image

image

**Issue: #3284**

### CODE REVIEW

**Review by ArtemHolikov — COMMENTED** [review]
image

Cover it by tests, please

File: src/redux/features/editProfileSlice.ts [hunk 1]
```diff
@@ -154,9 +154,8 @@ export const updateUser = createAsyncThunk(
     { rejectWithValue }
   ) => {
     try {
-      const response = await userService.updateUser(userId, params)
-      // eslint-disable-next-line @typescript-eslint/no-unsafe-return
-      return response.data
+      await userService.updateUser(userId, params)
+      return true
```
Comment (ArtemHolikov) [inline src/redux/features/editProfileSlice.ts]:
```suggestion
      await userService.updateUser(userId, params)
```

I don't think we need ```return true``` here. For what needs? We don't have to return true because you call the update function and it shouldn't return nothing. Or I am mistaken?

**Review by ArtemHolikov — CHANGES_REQUESTED** [review]

**Review by ArtemHolikov — CHANGES_REQUESTED** [review]
image

And cover your code by tests, please

File: src/redux/features/editProfileSlice.ts (hunk 1 above)
Comment (SofiiaYevush) [reply src/redux/features/editProfileSlice.ts]: My intention was to return `true` as a successful ending of `updateUser`, and for `fulfilled` state. 
But if you think it is unnecessary, I will test updating without `true`. It's good advice

Comment (ArtemHolikov) [reply src/redux/features/editProfileSlice.ts]: It will update user in successful ending. In case you get an error, ```catch``` block catchs it and returns with ```rejectWithValue```

**Comment by SofiiaYevush** [comment]
> image
> 
> And cover your code by tests, please

Covered)

File: src/redux/features/editProfileSlice.ts (hunk 1 above)
Comment (SofiiaYevush) [reply src/redux/features/editProfileSlice.ts]: You're right, that's true. Changed

File: src/redux/features/editProfileSlice.ts [hunk 2]
```diff
@@ -154,9 +154,8 @@ export const updateUser = createAsyncThunk(
     { rejectWithValue }
   ) => {
     try {
-      const response = await userService.updateUser(userId, params)
-      // eslint-disable-next-line @typescript-eslint/no-unsafe-return
-      return response.data
+      await userService.updateUser(userId, params)
+      return
```
Comment (ArtemHolikov) [inline src/redux/features/editProfileSlice.ts]:
```suggestion

```

I mean, u don't need ```return``` in general. Yes, it says that it completely finished, but it's just from stylistically side, no more.

**Review by ArtemHolikov — CHANGES_REQUESTED** [review]

**Review by nebby2105 — APPROVED** [review]

File: src/redux/features/editProfileSlice.ts (hunk 2 above)
Comment (SofiiaYevush) [reply src/redux/features/editProfileSlice.ts]: You're absolutely right) Changed

**Review by ArtemHolikov — APPROVED** [review]

**Review by markgol777 — APPROVED** [review]

**Review by Mav-Ivan — APPROVED** [review]
