### PR TITLE
Fixed changing a user photo in the header

### LINKED ISSUE #2521: (SP: 1) Fix changing a user photo in the header
Bug: after uploading a new photo, the photo doesn't changed in the header until the user reloads the page.

https://github.com/user-attachments/assets/2b1cbff9-6067-479b-9d4a-f0a63ced2025

### PR DESCRIPTION
**Pull request by Made1ra**
Before:

[image](https://private-user-images.githubusercontent.com/123400767/367610790-2b1cbff9-6067-479b-9d4a-f0a63ced2025.mov?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTE4NDgsIm5iZiI6MTczMjExMTU0OCwicGF0aCI6Ii8xMjM0MDA3NjcvMzY3NjEwNzkwLTJiMWNiZmY5LTYwNjctNDc5Yi05ZDRhLWYwYTYzY2VkMjAyNS5tb3Y_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxNDA1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGQyMWYwOGFmOGYwMjhjMDczNTVkMzc5OTA2NDkwNWZhNTdjMWI2Mjk1Mjk2NzRkODhlNGVjNTUwMGE4ZmE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.l2WLcqjQ4F-9JL-iCcIThtYIEubXHu6k1R6D4XJ26OI)

After:

https://github.com/user-attachments/assets/1bc861d9-11d1-4049-b3a7-cef0e87e9a26

### CODE REVIEW

File: src/containers/navigation-icons/AccountIcon.tsx [hunk 1]
```diff
@@ -37,6 +37,20 @@ const AccountIcon: FC<AccountIconProps> = ({ openMenu }) => {
     defaultResponse: defaultResponses.object as UserResponse
   })
 
+  const { photo: statePhoto } = useAppSelector((state) => state.editProfile)
+
+  const getAvatarSrc = useCallback(() => {
+    if (statePhoto && statePhoto.src) {
```
Comment (ipasic-softserve) [inline src/containers/navigation-icons/AccountIcon.tsx]: replace `statePhoto && statePhoto.src` with `statePhoto?.src` so it's more concise and easier to read

**Review by ipasic-softserve — APPROVED** [review]

File: src/containers/navigation-icons/AccountIcon.tsx [hunk 2]
```diff
@@ -37,6 +37,20 @@ const AccountIcon: FC<AccountIconProps> = ({ openMenu }) => {
...
+    if (statePhoto?.src) {
+      return statePhoto.src
+    }
+
+    if (photo) {
+      return createUrlPath(import.meta.env.VITE_APP_IMG_USER_URL || '', photo)
+    }
+  }, [photo, statePhoto])
+
+  const avatarSrc = getAvatarSrc()
```
Comment (Renatavl) [inline src/containers/navigation-icons/AccountIcon.tsx]: The final result of this code is just a variable, that's why it is better to use `useMemo()` instead of `useCallback()`

**Review by Renatavl — CHANGES_REQUESTED** [review]

**Review by Renatavl — APPROVED** [review]

**Review by luiqor — APPROVED** [review]
