### PR TITLE
Fixed Categories page not found error

### LINKED ISSUE #3137: (SP: ) Fix Categories Page not found
Actual result: Categories Page doesn't work.

Image

Image

Make Categories Page work again

### PR DESCRIPTION
**Pull request by VKormylo**
Fixed Categories page not found error. I refactored code so that it uses useQuery instead of useAxios for data fetching.
### Categories page:
image
### Subjects page:
image
### Subjects page filtered by category:
image

### CODE REVIEW

**Review by SofiiaYevush — APPROVED** [review]

File: src/hooks/use-load-more.tsx [hunk 1]
```diff
@@ -36,20 +42,20 @@ const useLoadMore = <Data, Params>({
...
-  const { response, loading, fetchData } = useAxios<
-    ItemsWithCount<Data>,
-    Params
-  >({
-    service,
-    defaultResponse: defaultResponses.itemsWithCount,
-    fetchOnMount: false,
-    onResponse: handleResponse
+  const { data: response, isFetching: loading } = useQuery({
+    queryFn: () => service({ ...params, limit, skip } as Params),
```
Comment (ShadowOfTheSpace) [inline src/hooks/use-load-more.tsx:46]: Why do you need to cast is to Params?

File: src/services/subject-service.ts [hunk 2]
```diff
@@ -4,14 +4,30 @@ import { AxiosResponse } from 'axios'
...
+import { getFullUrl } from '~/utils/get-full-url'
 
 export const subjectService = {
-  getSubjects: (
-    params?: Pick<SubjectInterface, 'name'>,
-    categoryId?: string
-  ): Promise<AxiosResponse<ItemsWithCount<SubjectInterface>>> => {
-    const category = createUrlPath(URLs.categories.get, categoryId)
-    return axiosClient.get(`${category}${URLs.subjects.get}`, { params })
+  getSubjects: (params?: Pick<SubjectInterface, 'name' | 'category'>) => {
```
Comment (ShadowOfTheSpace) [inline src/services/subject-service.ts]: Why `params` is optional?
```suggestion
  getSubjects: (params: Pick<SubjectInterface, 'name' | 'category'>) => {
```

File: src/services/subject-service.ts [hunk 3]
```diff
@@ -4,14 +4,30 @@ import { AxiosResponse } from 'axios'
...
+    const { category: { _id: categoryId } = {}, ...restParams } = params ?? {}
```
Comment (ShadowOfTheSpace) [inline src/services/subject-service.ts]:
```suggestion
    const { category, ...restParams } = params
```

File: src/constants/request.ts [hunk 4]
```diff
@@ -52,6 +52,7 @@ export const URLs = {
   },
   subjects: {
     get: '/subjects',
+    getByCategoryId: '/categories/:categoryId/subjects',
```
Comment (ShadowOfTheSpace) [inline src/constants/request.ts]: You don't need to add named parameters when there is only one of them
```suggestion
    getByCategoryId: '/categories/:id/subjects',
```

File: src/hooks/use-load-more.tsx [hunk 5]
```diff
@@ -36,20 +42,20 @@ const useLoadMore = <Data, Params>({
...
+    queryKey: [`load-more`, params, limit, skip],
```
Comment (ShadowOfTheSpace) [inline src/hooks/use-load-more.tsx]:
```suggestion
    queryKey: ['load-more', params, limit, skip],
```

File: src/pages/subjects/Subjects.tsx [hunk 6]
```diff
@@ -78,9 +78,9 @@ const Subjects = () => {
   }
 
   const getSubjects = useCallback(
-    (data?: Pick<SubjectInterface, 'name'>) =>
-      subjectService.getSubjects(data, categoryId),
-    [categoryId]
+    (data?: Pick<SubjectInterface, 'name' | 'category'>) =>
```
Comment (ShadowOfTheSpace) [inline src/pages/subjects/Subjects.tsx]: Why is it optional here? You replaced useAxios with useQuery here, so optionality is redundant here
```suggestion
    (data: Pick<SubjectInterface, 'name' | 'category'>) =>
```

File: src/pages/subjects/Subjects.tsx
Comment (ShadowOfTheSpace) [inline src/pages/subjects/Subjects.tsx:1]: Please, check how does Subects API work, probably `name` is not needed for requests. Probably only categoryId is needed

File: src/services/subject-service.ts [hunk 7]
```diff
@@ -4,14 +4,30 @@ import { AxiosResponse } from 'axios'
...
+      searchParameters: restParams
+    })
+
+    if (categoryId) {
+      resultUrl = getFullUrl({
+        pathname: URLs.subjects.getByCategoryId,
+        parameters: { categoryId },
+        searchParameters: restParams
+      })
+    }
```
Comment (ShadowOfTheSpace) [inline src/services/subject-service.ts]:
```suggestion
    if (category?._id) {
      resultUrl = getFullUrl({
        pathname: URLs.subjects.getByCategoryId,
        parameters: { id: category._id},
        searchParameters: restParams
      })
    }
```

File: src/types/services/types/services.types.ts [hunk 8]
```diff
@@ -18,9 +18,12 @@ export type ServiceFunction<Response, Params = undefined> = (
...
 
-export type ServiceFunctionNew<Response, Params = undefined> = (
-  params: Params extends undefined ? undefined : Params
-) => Promise<Response>
+export type ServiceFunctionNew<
+  Response,
+  Params = undefined
+> = Params extends undefined
+  ? () => Promise<Response>
+  : (params: Params) => Promise<Response>
```
Comment (ShadowOfTheSpace) [inline src/types/services/types/services.types.ts]: Please, make a rebase. This type is already as you need on develop branch

File: tests/unit/services/subject-service.spec.jsx [hunk 9]
```diff
@@ -0,0 +1,81 @@
...
+    vi.clearAllMocks()
+  })
+
+  it('should find subjects by categoryId', async () => {
+    const getFullUrlSpy = vi.spyOn(getFullUrl, 'getFullUrl')
+
+    mockAxiosClient
+      .onGet(
+        new RegExp(
+          URLs.subjects.getByCategoryId.replace(':categoryId', mockCategoryId)
```
Comment (ShadowOfTheSpace) [inline tests/unit/services/subject-service.spec.jsx]: Don't forget to change `categoryId` to `id` here

**Review by ShadowOfTheSpace — CHANGES_REQUESTED** [review]

File: src/hooks/use-load-more.tsx (hunk 1 above)
Comment (VKormylo) [reply src/hooks/use-load-more.tsx:46]: Without explicit casting there is type errors. I also can change that to `service({ ...(params as Params), limit, skip })` as well. What do you think about that change?

File: src/pages/subjects/Subjects.tsx
Comment (VKormylo) [reply src/pages/subjects/Subjects.tsx:1]: `name` is also needed because we can filter by categoryId and search by subject name.

File: src/services/subject-service.ts (hunk 2 above)
Comment (VKormylo) [reply src/services/subject-service.ts]: Yes, it shouldn't be optional, thank you. Fixed.

File: src/services/subject-service.ts (hunk 3 above)
Comment (VKormylo) [reply src/services/subject-service.ts]: Fixed.

File: src/constants/request.ts (hunk 4 above)
Comment (VKormylo) [reply src/constants/request.ts]: Fixed.

File: src/hooks/use-load-more.tsx (hunk 5 above)
Comment (VKormylo) [reply src/hooks/use-load-more.tsx]: Fixed.

File: src/pages/subjects/Subjects.tsx (hunk 6 above)
Comment (VKormylo) [reply src/pages/subjects/Subjects.tsx]: Yeah, true. Fixed.

File: src/services/subject-service.ts (hunk 7 above)
Comment (VKormylo) [reply src/services/subject-service.ts]: Fixed.

File: src/types/services/types/services.types.ts (hunk 8 above)
Comment (VKormylo) [reply src/types/services/types/services.types.ts]: Ok, thanks. Done.

File: tests/unit/services/subject-service.spec.jsx (hunk 9 above)
Comment (VKormylo) [reply tests/unit/services/subject-service.spec.jsx]: Yes, thanks. Fixed.

File: src/hooks/use-load-more.tsx (hunk 1 above)
Comment (ShadowOfTheSpace) [reply src/hooks/use-load-more.tsx:46]: I got it, leave it as it its

File: src/pages/subjects/Subjects.tsx [hunk 10]
```diff
@@ -78,9 +78,9 @@ const Subjects = () => {
   }
 
   const getSubjects = useCallback(
-    (data?: Pick<SubjectInterface, 'name'>) =>
-      subjectService.getSubjects(data, categoryId),
-    [categoryId]
+    (data: Pick<SubjectInterface, 'name' | 'category'>) =>
```
Comment (ShadowOfTheSpace) [inline src/pages/subjects/Subjects.tsx]: if only `categoryId` is needed, you can create type like 
`Pick<SubjectInterface, 'name'> & Record<'categoryId, string>`
You will have to pass just an `id` without mocking entire category.

**Review by ShadowOfTheSpace — CHANGES_REQUESTED** [review]

File: src/pages/subjects/Subjects.tsx (hunk 10 above)
Comment (VKormylo) [reply src/pages/subjects/Subjects.tsx]: I was thinking about alternative solution to that also, so thanks a lot. I will change that.

Comment (VKormylo) [reply src/pages/subjects/Subjects.tsx]: Fixed.

**Review by amoutens — APPROVED** [review]

**Review by ShadowOfTheSpace — APPROVED** [review]
