### PR TITLE
Replaced `useAxios` with `useQuery` and `useMutation` hooks on the Create Or Edit Lesson page

### LINKED ISSUE #3023: Replace `useAxios` with `useQuery` and `useMutation` hooks in the `CreateOrEditLesson.tsx`
**Description**
Replace the `useAxios` hook with the `useQuery` and `useMutation` hooks in the `CreateOrEditLesson.tsx` to improve data fetching, caching, and error handling.

**Tasks**

1. Identify all instances of `useAxios` usage in the `CreateOrEditLesson.tsx`.
2. Replace these instances with `useQuery` for GET methods and `useMutation` for PUT, PATCH, POST, DELETE methods, ensuring proper integration with the existing components.
3. Implement appropriate query keys to differentiate and cache the data effectively.
4. Update the related test cases (if any) to accommodate the changes.
5. Ensure backward compatibility with any existing functionality.

**Expected Outcome**

- The data-fetching logic  in the `CreateOrEditLesson.tsx` page utilizes `useQuery`.
- Enhanced data caching and better error handling.
- No regression in existing functionality.

### PR DESCRIPTION
**Pull request by Made1ra**
Replaced the `useAxios` hook with the `useQuery` and `useMutation` hooks on the Create Or Edit Lesson page to improve data fetching, caching, and error handling.

Screenshot 2025-01-01 at 23 52 51

Screenshot 2025-01-01 at 23 55 26

### CODE REVIEW

File: src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx [hunk 1]
```diff
@@ -165,44 +165,53 @@ const CreateOrEditLesson = () => {
...
+        fetchAddLesson()
+      }
+    },
     submitWithData: true
   })
 
-  const getLesson = (id?: string): Promise<AxiosResponse> => {
+  const getLesson = (id?: string) => {
     return ResourceService.getLesson(id)
   }
```
Comment (ShadowOfTheSpace) [inline src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx]: You can use closures here to encapsulate passing id to this function. It will help you to pass just reference to this function in the `queryFn` prop
```suggestion
  const getLesson = useCallback(() => {
    return ResourceService.getLesson(id)
  }, [id])
```

File: src/pages/lesson-details/LessonDetails.tsx [hunk 2]
```diff
@@ -42,17 +41,25 @@ const LessonDetails = () => {
...
+    queryFn: getLesson,
+    options: {
+      initialData: defaultResponse
+    }
   })
 
-  if (loading) return <Loader pageLoad />
+  if (isError) {
+    responseError()
+  }
```
Comment (ShadowOfTheSpace) [inline src/pages/lesson-details/LessonDetails.tsx]: Please never call a side-effect function directly inside a component. It can cause infinity rerenders, a `too many redirects` error, or other errors. Always use `useEffect` to call another function. This will guarantee that this function will be called only if `isError` changes.

File: src/pages/lesson-details/LessonDetails.tsx [hunk 3]
```diff
@@ -64,13 +71,13 @@ const LessonDetails = () => {
...
           resourceId={lessonId}
-          title={response.title}
+          title={data.title}
         />
       )
     })
   }
 
-  const attachmentsList = response.attachments.map((attachment) => (
+  const attachmentsList = data?.attachments?.map((attachment) => (
```
Comment (ShadowOfTheSpace) [inline src/pages/lesson-details/LessonDetails.tsx]: Why data is optional?

File: src/services/resource-service.ts
Comment (ShadowOfTheSpace) [inline src/services/resource-service.ts:1]: Please, use `getFullUrl` instead of `createUrlPath`. We will delete `createUrlPath` after replacing `useAxios` with `useQuery`

File: src/services/resource-service.ts [hunk 4]
```diff
@@ -43,22 +42,32 @@ export const ResourceService = {
...
     await axiosClient.delete(createUrlPath(URLs.resources.lessons.delete, id)),
-  addLesson: async (data: LessonData): Promise<AxiosResponse> =>
-    await axiosClient.post(URLs.resources.lessons.add, data),
-  editLesson: async (data: LessonData, id?: string): Promise<AxiosResponse> =>
-    await axiosClient.patch(
-      createUrlPath(URLs.resources.lessons.patch, id),
+  addLesson: async (data: LessonData) => {
+    return baseService.request<Lesson>({
+      method: 'POST',
+      url: createUrlPath(URLs.resources.lessons.add),
```
Comment (ShadowOfTheSpace) [inline src/services/resource-service.ts]: URL here doesn't have any dynamic params or search params, you can pass just url without `createUrlPath` call

**Review by ShadowOfTheSpace — CHANGES_REQUESTED** [review]

File: src/pages/lesson-details/LessonDetails.tsx (hunk 3 above)
Comment (Made1ra) [reply src/pages/lesson-details/LessonDetails.tsx]: Fixed it.

File: src/constants/request.ts [hunk 5]
```diff
@@ -71,9 +71,10 @@ export const URLs = {
   resources: {
     lessons: {
       add: '/lessons',
-      get: '/lessons',
+      get: '/lessons/',
```
Comment (ShadowOfTheSpace) [inline src/constants/request.ts]:
```suggestion
      get: '/lessons',
```

File: src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx [hunk 6]
```diff
@@ -125,32 +129,18 @@ const CreateOrEditLesson = () => {
     handleNonInputValueChange('content', content)
   }
 
-  const addLesson = (): Promise<AxiosResponse> => {
+  const addLesson = (): Promise<Lesson> => {
```
Comment (ShadowOfTheSpace) [inline src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx]: It's redundant here, this function is typed automatically
```suggestion
  const addLesson = () => {
```

File: src/services/resource-service.ts [hunk 7]
```diff
@@ -43,22 +42,38 @@ export const ResourceService = {
...
+  addLesson: async (data: LessonData) => {
+    return baseService.request<Lesson>({
+      method: 'POST',
+      url: URLs.resources.lessons.add,
       data
-    ),
+    })
+  },
+  editLesson: async (data: LessonData, id: string) => {
+    return baseService.request<Lesson>({
```
Comment (ShadowOfTheSpace) [inline src/services/resource-service.ts]: Check the backend response, probably there is nothing in body.
```suggestion
    return baseService.request<void>({
```

File: src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx [hunk 8]
```diff
@@ -165,44 +155,71 @@ const CreateOrEditLesson = () => {
...
-  }
+  })
+
+  const editLesson = useCallback(async () => {
+    if (id) {
+      return ResourceService.editLesson(data, id)
+    }
+
+    return Promise.resolve(defaultResponse)
+  }, [data, id])
```
Comment (ShadowOfTheSpace) [inline src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx]: If the backend doesn't return something, you can just conditionaly call service without any return value
```suggestion
  const editLesson = useCallback(async () => {
    if (id) {
      await ResourceService.editLesson(data, id)
    }
  }, [data, id])
```

File: src/types/my-resources/interfaces/myResources.interface.ts [hunk 9]
```diff
@@ -18,7 +17,7 @@ export interface Lesson extends CommonEntityFields, ResourceBase {
   author: string
   content: string
   attachments: Attachment[]
-  category: Category | null
+  category: string | null
```
Comment (ShadowOfTheSpace) [inline src/types/my-resources/interfaces/myResources.interface.ts]: This change broke typescript in these files:
```
src\containers\my-resources\lessons-container\LessonsContainer.constants.tsx
```
```
src\containers\add-resources\AddLessons.constants.tsx
```
```
src\containers\add-resources\AddResources.tsx
```

File: tests/unit/pages/create-or-edit-lesson/CreateOrEditLessonWithId.spec.jsx [hunk 10]
```diff
@@ -23,34 +23,27 @@ vi.mock('react-router-dom', async () => ({
...
 
-describe('CreateOrEditLesson component with id', () => {
+describe('CreateOrEditLesson with id', () => {
   beforeAll(() => {
-    mockAxiosClient
-      .onGet(createUrlPath(URLs.resources.lessons.get, mockParams.id))
-      .reply(200, mockLesson)
+    vi.spyOn(baseService, 'request').mockImplementation((config) => {
+      if (config.method === 'PATCH') {
+        return Promise.resolve({ data: {} })
```
Comment (ShadowOfTheSpace) [inline tests/unit/pages/create-or-edit-lesson/CreateOrEditLessonWithId.spec.jsx]:
```suggestion
        return Promise.resolve()
```

File: src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx [hunk 11]
```diff
@@ -165,44 +155,71 @@ const CreateOrEditLesson = () => {
...
     initialValues,
     validations,
-    onSubmit: id ? fetchEditedLesson : fetchAddLesson,
+    onSubmit: () => {
+      if (id) {
+        fetchEditedLesson()
+      } else {
+        fetchAddLesson()
+      }
+    },
```
Comment (ShadowOfTheSpace) [inline src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx:148]: Why did you change that?

**Review by ShadowOfTheSpace — CHANGES_REQUESTED** [review]

File: src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx [hunk 12]
```diff
@@ -165,44 +155,71 @@ const CreateOrEditLesson = () => {
...
+    }
+  }, [error, handleResponseError])
 
-  if (getLessonLoading) {
+  if (isLoading) {
     return <Loader pageLoad />
   }
 
-  const attachmentsList = data.attachments.map((attachment) => (
+  const attachmentsList = data?.attachments?.map((attachment) => (
```
Comment (ShadowOfTheSpace) [inline src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx]: Also, please, remove `?` here
```suggestion
  const attachmentsList = data.attachments?.map((attachment) => (
```

**Review by ShadowOfTheSpace — CHANGES_REQUESTED** [review]

File: src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx (hunk 11 above)
Comment (Made1ra) [reply src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx:148]: There is an error if I am doing it like that


Screenshot 2025-01-07 at 19 16 51

File: src/types/my-resources/interfaces/myResources.interface.ts (hunk 9 above)
Comment (Made1ra) [reply src/types/my-resources/interfaces/myResources.interface.ts]: I've fixed TypeScript errors in LessonsContainer and AddLessons, but I don't see any problem in AddResourses.

Comment (ShadowOfTheSpace) [reply src/types/my-resources/interfaces/myResources.interface.ts]: Sorry about `AddResourses`, probably ts didn't fully reload after I changed the branch

File: src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx [hunk 13]
```diff
@@ -60,23 +59,26 @@ const CreateOrEditLesson = () => {
   const navigate = useNavigate()
   const { id } = useParams()
 
-  const handleResponseError = (error?: ErrorResponse) => {
-    const errorKey = getErrorKey(error)
+  const handleResponseError = useCallback(
+    (error?: ErrorResponse | ResponseError) => {
```
Comment (ShadowOfTheSpace) [inline src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx]: You can leave it here like that because there is only `ResponseError` used. Also it's never optional
```suggestion
    (error: ResponseError) => {
```

**Review by ShadowOfTheSpace — CHANGES_REQUESTED** [review]

File: src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx [hunk 14]
```diff
@@ -60,23 +58,26 @@ const CreateOrEditLesson = () => {
...
+                options: {
+                  message: getErrorMessage(error.message)
+                }
               }
-            }
-          : errorKey
-      })
-    )
-  }
+            : errorKey
```
Comment (ShadowOfTheSpace) [inline src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx]: Error isn't optional right now, you can remove this ternary operator

**Review by ShadowOfTheSpace — CHANGES_REQUESTED** [review]

File: src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx [hunk 15]
```diff
@@ -60,23 +58,24 @@ const CreateOrEditLesson = () => {
   const navigate = useNavigate()
   const { id } = useParams()
 
-  const handleResponseError = (error?: ErrorResponse) => {
-    const errorKey = getErrorKey(error)
+  const handleResponseError = useCallback(
+    (error: ResponseError) => {
+      const errorKey = getErrorKey(error)
```
Comment (ShadowOfTheSpace) [inline src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx]: I think you can remove this extra variable here and put `getErrorKey` call directly

File: src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx [hunk 16]
```diff
@@ -125,32 +124,18 @@ const CreateOrEditLesson = () => {
     handleNonInputValueChange('content', content)
   }
 
-  const addLesson = (): Promise<AxiosResponse> => {
+  const addLesson = () => {
```
Comment (ShadowOfTheSpace) [inline src/pages/create-or-edit-lesson/CreateOrEditLesson.tsx]: Please, add `useCallback` to this function, as you pass it into `useMutation` hook

**Review by ShadowOfTheSpace — CHANGES_REQUESTED** [review]

**Review by ShadowOfTheSpace — APPROVED** [review]

**Review by markgol777 — APPROVED** [review]

**Review by Mike-Popovych — APPROVED** [review]
