### PR TITLE
Bugfix/3214/fix div inside p warning in cooperationdetails

### LINKED ISSUE #3214: Fix warning about usage <div> tag inside <p> tag in CooperationDetails component
Currently, there is a warning inside `CooperationDetails` tests about incorrect usage of HTML tags. Investigate in which component it happens and fix that if possible.

Full logs:

Image

### PR DESCRIPTION
**Pull request by danikua**
Refactor `AcceptCooperationClosing`  and `CooperationClosureDeclinedBanner `components to fix invalid HTML nesting:

Before:
image

After: 
image

### CODE REVIEW

**Review by ArtemHolikov — APPROVED** [review]

File: src/components/active-students/ActiveStudentsBlock.tsx
Comment (ShadowOfTheSpace) [inline src/components/active-students/ActiveStudentsBlock.tsx:1]: How changes in this file are related to this task? If this file came from another branch (I guess it's related to [this](https://github.com/ita-social-projects/SpaceToStudy-Client/pull/3332) PR), you should do a rebase.

File: src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.tsx [hunk 1]
```diff
@@ -60,13 +60,13 @@ const AcceptCooperationClosing: React.FC<AcceptCooperationClosureProps> = ({
           </Typography>
           {t('cooperationDetailsPage.closingMessage2')}
           {message && (
-            <Box sx={styles.response}>
+            <Box component='span' sx={{ ...styles.response, display: 'block' }}>
```
Comment (ShadowOfTheSpace) [inline src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.tsx]: Can we move that to the `styles` file without breaking the layout?
```suggestion
            <Box component='span' sx={styles.response}>
```

File: src/components/active-students/ActiveStudentsBlock.tsx
Comment (danikua) [reply src/components/active-students/ActiveStudentsBlock.tsx:1]: I\`ve arleady merged this [PR](https://github.com/ita-social-projects/SpaceToStudy-Client/pull/3332), so anyway it won\`t breake anything

File: src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.tsx (hunk 1 above)
Comment (danikua) [reply src/containers/my-cooperations/accept-cooperation-close/AcceptCooperationClosing.tsx]: Changed this one, thanks for suggestion

File: src/components/active-students/ActiveStudentsBlock.tsx
Comment (ShadowOfTheSpace) [reply src/components/active-students/ActiveStudentsBlock.tsx:1]: Yep, it won't break anything, but we don't need to see unrelevant changes in PR. Please, do a rebase

Comment (danikua) [reply src/components/active-students/ActiveStudentsBlock.tsx:1]: Done

Comment (ShadowOfTheSpace) [reply src/components/active-students/ActiveStudentsBlock.tsx:1]: Great, thank you!

**Review by IrynaKhylchuk — APPROVED** [review]

**Review by Mav-Ivan — APPROVED** [review]
