### PR TITLE
Fixed the switcher

### LINKED ISSUE #3179: (SP:) Fix switcher on find offers page
Image

### PR DESCRIPTION
**Pull request by Mav-Ivan**
The switcher now matches the displayed offers

https://github.com/user-attachments/assets/3d6d5efa-dc81-48b3-a1b4-79c465fe7c43

### CODE REVIEW

**Review by Made1ra — APPROVED** [review]

**Review by Mike-Popovych — APPROVED** [review]

**Review by amoutens — APPROVED** [review]

File: src/components/app-content-switcher/AppContentSwitcher.tsx [hunk 1]
```diff
@@ -14,14 +14,16 @@ interface SwitcherProps {
   switchOptions: SwitchOptions
   typographyVariant: TypographyProps['variant']
   styles?: SxProps
+  checked?: boolean
```
Comment (ShadowOfTheSpace) [inline src/components/app-content-switcher/AppContentSwitcher.tsx]: `checked` is a value, `defaultChecked` is a initial value
```suggestion
  defaultChecked?: boolean
```

**Review by ShadowOfTheSpace — CHANGES_REQUESTED** [review]

**Review by ShadowOfTheSpace — APPROVED** [review]
Approved, but don't forget to resolve this issue with naming

File: src/components/app-content-switcher/AppContentSwitcher.tsx (hunk 1 above)
Comment (Mav-Ivan) [reply src/components/app-content-switcher/AppContentSwitcher.tsx]: agree , fixed
